ORDER_STATUS_PENDING = "PENDING"
ORDER_STATUS_READY = "READY"
ORDER_STATUS_DELIVERED = "DELIVERED"
ORDER_STATUS_CANCELED = "CANCELED"

VALID_ORDER_STATUSES = {
    ORDER_STATUS_PENDING,
    ORDER_STATUS_READY,
    ORDER_STATUS_DELIVERED,
    ORDER_STATUS_CANCELED,
}

ORDER_PAYMENT_TYPE_ADVANCE = "ADVANCE"
ORDER_PAYMENT_TYPE_SETTLEMENT = "SETTLEMENT"
ORDER_PAYMENT_TYPE_REFUND = "REFUND"

VALID_ORDER_PAYMENT_TYPES = {
    ORDER_PAYMENT_TYPE_ADVANCE,
    ORDER_PAYMENT_TYPE_SETTLEMENT,
    ORDER_PAYMENT_TYPE_REFUND,
}

ORDER_PAYMENT_METHOD_CASH = "CASH"
ORDER_PAYMENT_METHOD_CARD = "CARD"
ORDER_PAYMENT_METHOD_MIXED = "MIXED"

VALID_ORDER_PAYMENT_METHOD_CODES = {
    ORDER_PAYMENT_METHOD_CASH,
    ORDER_PAYMENT_METHOD_CARD,
    ORDER_PAYMENT_METHOD_MIXED,
}

OUTBOX_EVENT_ORDER_CREATED_V1 = "order.created.v1"
OUTBOX_EVENT_ORDER_READY_V1 = "order.ready.v1"
OUTBOX_EVENT_ORDER_DELIVERED_V1 = "order.delivered.v1"
OUTBOX_EVENT_ORDER_CANCELED_V1 = "order.canceled.v1"
