PRODUCTION_STATUS_DRAFT = "DRAFT"
PRODUCTION_STATUS_IN_PROGRESS = "IN_PROGRESS"
PRODUCTION_STATUS_COMPLETED = "COMPLETED"
PRODUCTION_STATUS_CANCELLED = "CANCELLED"

PRODUCTION_INPUT_STATUS_AVAILABLE = "available"
PRODUCTION_INPUT_STATUS_INSUFFICIENT = "insufficient"
PRODUCTION_INPUT_STATUS_UNAVAILABLE = "unavailable"

PRODUCTION_SOURCE_DOCUMENT_TYPE = "PRODUCTION_BATCH"
PRODUCTION_RESOURCE_TYPE = "production_batch"

INVENTORY_MOVEMENT_TYPE_PRODUCTION_CONSUMPTION = "PRODUCTION_CONSUMPTION"
INVENTORY_MOVEMENT_TYPE_PRODUCTION_OUTPUT = "PRODUCTION_OUTPUT"

AUDIT_ACTION_ADMIN_PRODUCTION_CREATED = "admin.production.created"
AUDIT_ACTION_ADMIN_PRODUCTION_UPDATED = "admin.production.updated"
AUDIT_ACTION_ADMIN_PRODUCTION_STARTED = "admin.production.started"
AUDIT_ACTION_ADMIN_PRODUCTION_COMPLETED = "admin.production.completed"
AUDIT_ACTION_ADMIN_PRODUCTION_CANCELLED = "admin.production.cancelled"

OUTBOX_EVENT_ADMIN_PRODUCTION_CREATED_V1 = "admin.production.created.v1"
OUTBOX_EVENT_ADMIN_PRODUCTION_UPDATED_V1 = "admin.production.updated.v1"
OUTBOX_EVENT_ADMIN_PRODUCTION_STARTED_V1 = "admin.production.started.v1"
OUTBOX_EVENT_ADMIN_PRODUCTION_COMPLETED_V1 = "admin.production.completed.v1"
OUTBOX_EVENT_ADMIN_PRODUCTION_CANCELLED_V1 = "admin.production.cancelled.v1"

VALID_PRODUCTION_STATUSES = {
    PRODUCTION_STATUS_DRAFT,
    PRODUCTION_STATUS_IN_PROGRESS,
    PRODUCTION_STATUS_COMPLETED,
    PRODUCTION_STATUS_CANCELLED,
}

VALID_PRODUCTION_INPUT_STATUSES = {
    PRODUCTION_INPUT_STATUS_AVAILABLE,
    PRODUCTION_INPUT_STATUS_INSUFFICIENT,
    PRODUCTION_INPUT_STATUS_UNAVAILABLE,
}
