import type {
  AdminModuleDefinition,
  AdminModuleKey,
  AdminSectionDefinition,
  AdminSectionKey,
  AdminScopeFilterKind,
  AdminTableColumn,
} from "./adminTypes";

const defaultOperationalFilters: AdminScopeFilterKind[] = [
  "branch",
  "brand",
  "dateRange",
  "status",
];
const defaultCatalogFilters: AdminScopeFilterKind[] = ["branch", "brand", "status", "search"];
const defaultFinanceFilters: AdminScopeFilterKind[] = [
  "branch",
  "brand",
  "dateRange",
  "status",
  "shift",
  "user",
];

export const adminSections: AdminSectionDefinition[] = [
  {
    key: "principal",
    title: "Principal",
    description: "Centro de mando y trabajo pendiente.",
  },
  {
    key: "catalogCosts",
    title: "Catálogo y costos",
    description: "Productos, precios, recetas y descuentos.",
  },
  {
    key: "salesOrders",
    title: "Ventas y pedidos",
    description: "Ventas, pedidos, devoluciones y correcciones.",
  },
  {
    key: "multibranchOperations",
    title: "Operación multisucursal",
    description: "Sucursales, inventario, transferencias y producción.",
  },
  {
    key: "purchasesSupply",
    title: "Compras y abastecimiento",
    description: "Proveedores, compras e insumos.",
  },
  {
    key: "cashFinance",
    title: "Caja y finanzas",
    description: "Cortes, conciliación, pagos y flujo de efectivo.",
  },
  {
    key: "qualityHygiene",
    title: "Calidad e higiene",
    description: "Limpieza, verificaciones, incidencias y mantenimiento.",
  },
  {
    key: "control",
    title: "Control",
    description: "Usuarios, permisos, auditoría, reportes y configuración.",
  },
];

function columns(labels: string[]): AdminTableColumn[] {
  return labels.map((label) => ({
    key: label
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, ""),
    label,
  }));
}

function moduleDefinition(
  definition: Omit<AdminModuleDefinition, "path"> & { routeSlug: string },
): AdminModuleDefinition {
  return {
    ...definition,
    path: `/admin/${definition.routeSlug}`,
  };
}

export const adminModules: AdminModuleDefinition[] = [
  moduleDefinition({
    key: "dashboard",
    routeSlug: "dashboard",
    sectionKey: "principal",
    title: "Dashboard",
    description: "Resumen ejecutivo multisucursal para ventas, caja, merma, pedidos e inventario.",
    status: "partial",
    actionLabel: "Ver alertas",
    filters: ["branch", "brand", "dateRange"],
    metrics: [
      { key: "sales", label: "Ventas del día", value: "Sin datos", tone: "info" },
      {
        key: "cash-differences",
        label: "Diferencias de caja",
        value: "Sin datos",
        tone: "warning",
      },
      { key: "waste", label: "Merma del día", value: "Sin datos", tone: "danger" },
      { key: "orders", label: "Pedidos pendientes", value: "Sin datos", tone: "default" },
      { key: "cleaning", label: "Limpieza pendiente", value: "Sin datos", tone: "success" },
      { key: "inventory", label: "Inventario crítico", value: "Sin datos", tone: "warning" },
    ],
    tableColumns: columns(["Indicador", "Sucursal", "Estado", "Última actualización"]),
    emptyDescription:
      "Aquí se consolidarán métricas reales cuando los endpoints ejecutivos estén disponibles.",
    detailTitle: "Lectura ejecutiva",
    auditEntityType: "admin_dashboard",
    permissionActions: ["view", "export"],
  }),
  moduleDefinition({
    key: "alerts",
    routeSlug: "alertas",
    sectionKey: "principal",
    title: "Alertas y tareas",
    description:
      "Concentra inventario bajo, cierres faltantes, limpieza pendiente y operaciones por revisar.",
    status: "partial",
    filters: ["branch", "brand", "dateRange", "status", "user"],
    metrics: [
      { key: "critical", label: "Críticas", value: "Sin datos", tone: "danger" },
      { key: "pending", label: "Pendientes", value: "Sin datos", tone: "warning" },
      { key: "today", label: "Para hoy", value: "Sin datos", tone: "info" },
    ],
    tableColumns: columns(["Prioridad", "Sucursal", "Módulo", "Tarea", "Estado", "Responsable"]),
    emptyDescription:
      "Aquí aparecerán tareas como producto sin precio, receta incompleta o transferencia pendiente.",
    detailTitle: "Detalle de alerta",
    auditEntityType: "admin_alert",
    permissionActions: ["view", "update"],
  }),
  moduleDefinition({
    key: "products",
    routeSlug: "productos",
    sectionKey: "catalogCosts",
    title: "Productos",
    description:
      "Administra productos vendidos y producidos, disponibilidad por sucursal y tipo de venta.",
    status: "preparation",
    actionLabel: "Nuevo producto",
    filters: defaultCatalogFilters,
    metrics: [
      { key: "active", label: "Activos", value: "Sin datos", tone: "success" },
      { key: "inactive", label: "Inactivos", value: "Sin datos" },
      { key: "missing-price", label: "Sin precio", value: "Sin datos", tone: "warning" },
    ],
    tableColumns: columns(["Producto", "Categoría / clase", "Tipo de venta", "Ámbito", "Estado"]),
    emptyDescription:
      "Aquí se listarán productos globales, por marca o por sucursal con su relación a recetas y costos.",
    detailTitle: "Detalle del producto",
    auditEntityType: "product",
    permissionActions: ["view", "create", "update", "delete", "export"],
  }),
  moduleDefinition({
    key: "categories",
    routeSlug: "categorias",
    sectionKey: "catalogCosts",
    title: "Categorías / clases",
    description: "Administra clases operativas usadas por POS, producción y captura por clase.",
    status: "partial",
    actionLabel: "Nueva clase",
    filters: defaultCatalogFilters,
    metrics: [
      { key: "classes", label: "Clases", value: "Sin datos", tone: "info" },
      { key: "products", label: "Productos asociados", value: "Sin datos" },
    ],
    tableColumns: columns(["Clase", "Uso operativo", "Productos", "Ámbito", "Estado"]),
    emptyDescription:
      "Aquí se controlará la estructura de clases respetando PRODUCT_DIRECT y CLASS_CAPTURE.",
    detailTitle: "Detalle de categoría",
    auditEntityType: "product_class",
    permissionActions: ["view", "create", "update", "delete", "export"],
  }),
  moduleDefinition({
    key: "recipesCosts",
    routeSlug: "recetas-costos",
    sectionKey: "catalogCosts",
    title: "Recetas y costos",
    description: "Prepara recetas, insumos, rendimiento esperado, costo teórico y margen estimado.",
    status: "partial",
    actionLabel: "Nueva receta",
    filters: ["branch", "brand", "status", "search"],
    metrics: [
      { key: "recipes", label: "Recetas", value: "Sin datos" },
      { key: "incomplete", label: "Incompletas", value: "Sin datos", tone: "warning" },
      { key: "margin", label: "Margen estimado", value: "Sin datos", tone: "info" },
    ],
    tableColumns: columns(["Receta", "Producto", "Rendimiento", "Costo teórico", "Estado"]),
    emptyDescription:
      "Aquí se conectarán recetas con insumos, costos reales y merma de producción.",
    detailTitle: "Detalle de receta",
    auditEntityType: "recipe",
    permissionActions: ["view", "create", "update", "export"],
  }),
  moduleDefinition({
    key: "prices",
    routeSlug: "precios",
    sectionKey: "catalogCosts",
    title: "Precios",
    description:
      "Gobierna precios comerciales vigentes desde su fuente canonica: producto o clase.",
    status: "partial",
    filters: defaultCatalogFilters,
    metrics: [
      { key: "active", label: "Precios activos", value: "Sin datos", tone: "success" },
      { key: "direct", label: "Producto directo", value: "Sin datos", tone: "info" },
      { key: "class", label: "Captura por clase", value: "Sin datos", tone: "info" },
      { key: "missing", label: "Sin precio valido", value: "Sin datos", tone: "warning" },
    ],
    tableColumns: columns(["Entidad", "Propietario", "Precio", "Costo", "Salud", "Estado"]),
    emptyDescription:
      "Aqui apareceran productos PRODUCT_DIRECT y clases CLASS_CAPTURE con precio efectivo.",
    detailTitle: "Detalle de precio",
    auditEntityType: "price_rule",
    permissionActions: ["view", "update", "export"],
  }),
  moduleDefinition({
    key: "discounts",
    routeSlug: "descuentos",
    sectionKey: "catalogCosts",
    title: "Descuentos",
    description: "Gobierna reglas comerciales de descuento, alcance, vigencia y salud operativa.",
    status: "partial",
    actionLabel: "Nuevo descuento",
    filters: defaultCatalogFilters,
    metrics: [
      { key: "active", label: "Activos", value: "Sin datos", tone: "success" },
      { key: "upcoming", label: "Proximos", value: "Sin datos", tone: "info" },
      { key: "warnings", label: "Con advertencias", value: "Sin datos", tone: "warning" },
    ],
    tableColumns: columns([
      "Descuento",
      "Tipo",
      "Alcance",
      "Objetivo",
      "Valor",
      "Vigencia",
      "Salud",
    ]),
    emptyDescription:
      "Aqui se administraran definiciones comerciales, no descuentos ya aplicados a tickets.",
    detailTitle: "Detalle de descuento",
    auditEntityType: "discount",
    permissionActions: ["view", "create", "update", "void", "export"],
  }),
  moduleDefinition({
    key: "sales",
    routeSlug: "ventas",
    sectionKey: "salesOrders",
    title: "Ventas / tickets",
    description: "Consulta ventas emitidas por sucursal, cajero, método de pago, total y estado.",
    status: "partial",
    filters: defaultFinanceFilters,
    metrics: [
      { key: "sales", label: "Ventas del periodo", value: "API", tone: "info" },
      { key: "tickets", label: "Tickets emitidos", value: "API", tone: "info" },
      { key: "average", label: "Ticket promedio", value: "API" },
    ],
    tableColumns: columns([
      "Ticket",
      "Fecha",
      "Sucursal",
      "Cajero",
      "Método de pago",
      "Total",
      "Estado",
    ]),
    emptyDescription:
      "Aquí se consultarán ventas reales y su relación con devoluciones, correcciones y reimpresiones.",
    detailTitle: "Detalle de venta",
    auditEntityType: "sale_ticket",
    permissionActions: ["view", "export"],
  }),
  moduleDefinition({
    key: "orders",
    routeSlug: "pedidos",
    sectionKey: "salesOrders",
    title: "Pedidos",
    description: "Consulta pedidos por entrega, anticipo, saldo, estado, sucursal y cliente.",
    status: "partial",
    filters: defaultOperationalFilters,
    metrics: [
      { key: "pending", label: "Pendientes", value: "API", tone: "warning" },
      { key: "ready", label: "Listos", value: "API", tone: "info" },
      { key: "balance", label: "Saldo pendiente", value: "API" },
    ],
    tableColumns: columns([
      "Folio",
      "Cliente",
      "Entrega",
      "Sucursal",
      "Anticipo",
      "Pendiente",
      "Estado",
    ]),
    emptyDescription:
      "Aquí se dará seguimiento a apartados, entregas, cancelaciones e impacto en caja.",
    detailTitle: "Detalle de pedido",
    auditEntityType: "customer_order",
    permissionActions: ["view", "export"],
  }),
  moduleDefinition({
    key: "returnsCorrections",
    routeSlug: "devoluciones-correcciones",
    sectionKey: "salesOrders",
    title: "Devoluciones / correcciones",
    description:
      "Consulta devoluciones, reembolsos y ajustes auditados con trazabilidad a documentos origen.",
    status: "partial",
    filters: defaultFinanceFilters,
    metrics: [
      { key: "returns", label: "Devoluciones", value: "API", tone: "warning" },
      { key: "corrections", label: "Correcciones", value: "API", tone: "info" },
      { key: "cash-impact", label: "Impacto en caja", value: "API" },
    ],
    tableColumns: columns([
      "Folio",
      "Ticket relacionado",
      "Sucursal",
      "Usuario",
      "Monto",
      "Estado",
    ]),
    emptyDescription:
      "Aquí se auditarán devoluciones y correcciones sin permitir borrado físico sensible.",
    detailTitle: "Detalle de reversa",
    auditEntityType: "return_or_correction",
    permissionActions: ["view", "void", "export"],
  }),
  moduleDefinition({
    key: "branches",
    routeSlug: "sucursales",
    sectionKey: "multibranchOperations",
    title: "Sucursales",
    description:
      "Administra sucursales, marca, dirección, zona, estado y configuración operativa básica.",
    status: "ready",
    actionLabel: "Nueva sucursal",
    filters: ["branch", "brand", "status", "search"],
    metrics: [
      { key: "branches", label: "Sucursales", value: "API", tone: "info" },
      { key: "active", label: "Activas", value: "API", tone: "success" },
    ],
    tableColumns: columns(["Código", "Sucursal", "Marca", "Estaciones", "Usuarios", "Estado"]),
    emptyDescription: "Aquí se administra la red multisucursal con datos reales del backend.",
    detailTitle: "Detalle de sucursal",
    auditEntityType: "branch",
    permissionActions: ["view", "create", "update", "configure", "export"],
  }),
  moduleDefinition({
    key: "registersStations",
    routeSlug: "cajas-estaciones",
    sectionKey: "multibranchOperations",
    title: "Cajas / estaciones",
    description:
      "Administra estaciones POS, codigos de workstation, sucursal vinculada y estado operativo.",
    status: "ready",
    actionLabel: "Nueva estacion",
    filters: ["branch", "status", "search"],
    metrics: [
      { key: "stations", label: "Estaciones", value: "API", tone: "info" },
      { key: "active", label: "Activas", value: "API", tone: "success" },
      { key: "open-cash", label: "Caja abierta", value: "API", tone: "warning" },
    ],
    tableColumns: columns([
      "Estacion",
      "Codigo",
      "Sucursal",
      "Caja actual",
      "Preparacion",
      "Estado",
    ]),
    emptyDescription:
      "Aqui se administran estaciones POS reales sin duplicar cierres de caja ni sucursales.",
    detailTitle: "Detalle de estacion",
    auditEntityType: "workstation",
    permissionActions: ["view", "create", "update", "configure", "export"],
  }),
  moduleDefinition({
    key: "inventory",
    routeSlug: "inventario",
    sectionKey: "multibranchOperations",
    title: "Inventario",
    description: "Consulta existencias por sucursal, movimientos y ajustes auditados.",
    status: "ready",
    actionLabel: "Nuevo ajuste",
    filters: ["branch", "status", "search"],
    metrics: [
      { key: "with-stock", label: "Con existencia", value: "API", tone: "success" },
      { key: "negative", label: "Stock negativo", value: "API", tone: "danger" },
      { key: "stale", label: "Sin movimiento", value: "API", tone: "warning" },
    ],
    tableColumns: columns([
      "Producto / insumo",
      "Sucursal",
      "Ubicacion",
      "Existencia",
      "Ultimo movimiento",
      "Alertas",
    ]),
    emptyDescription:
      "Aqui se consultan existencias reales; ninguna modificacion se hace sin movimiento auditable.",
    detailTitle: "Detalle de inventario",
    auditEntityType: "inventory_balance",
    permissionActions: ["view", "create", "update", "export"],
  }),
  moduleDefinition({
    key: "transfers",
    routeSlug: "transferencias",
    sectionKey: "multibranchOperations",
    title: "Transferencias",
    description:
      "Gestiona envios, recepciones, diferencias e impacto de inventario entre sucursales.",
    status: "ready",
    actionLabel: "Nueva transferencia",
    filters: defaultOperationalFilters,
    metrics: [
      { key: "sent", label: "En transito", value: "API", tone: "info" },
      { key: "pending", label: "Por recibir", value: "API", tone: "warning" },
      { key: "differences", label: "Con diferencia", value: "API", tone: "danger" },
    ],
    tableColumns: columns([
      "Folio",
      "Origen",
      "Destino",
      "Enviado",
      "Recibido",
      "Diferencia",
      "Estado",
    ]),
    emptyDescription: "Aqui aparecen transferencias persistidas sin duplicar inventario ni POS.",
    detailTitle: "Detalle de transferencia",
    auditEntityType: "branch_transfer",
    permissionActions: ["view", "void", "export"],
  }),
  moduleDefinition({
    key: "production",
    routeSlug: "produccion",
    sectionKey: "multibranchOperations",
    title: "Producción",
    description:
      "Planea, ejecuta y cierra lotes con receta, insumos, rendimiento e impacto de inventario.",
    status: "ready",
    actionLabel: "Nueva produccion",
    filters: defaultOperationalFilters,
    metrics: [
      { key: "planned", label: "Pendientes", value: "API", tone: "info" },
      { key: "in-progress", label: "En proceso", value: "API", tone: "warning" },
      { key: "variance", label: "Con variacion", value: "API", tone: "warning" },
    ],
    tableColumns: columns([
      "Folio",
      "Sucursal",
      "Producto",
      "Receta",
      "Planeado",
      "Producido",
      "Variacion",
      "Estado",
    ]),
    emptyDescription:
      "Aqui se gestionan lotes persistidos; el inventario solo cambia con cierre auditado.",
    detailTitle: "Detalle de producción",
    auditEntityType: "production_order",
    permissionActions: ["view", "create", "update", "void", "export"],
  }),
  moduleDefinition({
    key: "waste",
    routeSlug: "merma",
    sectionKey: "multibranchOperations",
    title: "Merma",
    description:
      "Registra, consulta y audita merma por sucursal, producto, motivo, origen e impacto operativo.",
    status: "ready",
    actionLabel: "Nueva merma",
    filters: defaultOperationalFilters,
    metrics: [
      { key: "records", label: "Mermas", value: "API", tone: "warning" },
      { key: "high-impact", label: "Alto impacto", value: "API", tone: "danger" },
      { key: "estimated-value", label: "Valor estimado", value: "API", tone: "info" },
    ],
    tableColumns: columns([
      "Folio",
      "Fecha",
      "Sucursal",
      "Producto",
      "Motivo",
      "Cantidad",
      "Impacto",
    ]),
    emptyDescription:
      "Aqui se revisa y confirma merma persistida con impacto de inventario auditable.",
    detailTitle: "Detalle de merma",
    auditEntityType: "waste_record",
    permissionActions: ["view", "create", "export"],
  }),
  moduleDefinition({
    key: "suppliers",
    routeSlug: "proveedores",
    sectionKey: "purchasesSupply",
    title: "Proveedores",
    description:
      "Administra proveedores, contactos, condiciones comerciales, productos surtidos y estado operativo.",
    status: "ready",
    actionLabel: "Nuevo proveedor",
    filters: ["branch", "status", "search"],
    metrics: [
      { key: "total", label: "Proveedores", value: "API", tone: "info" },
      { key: "active", label: "Activos", value: "API", tone: "success" },
      { key: "warnings", label: "Advertencias", value: "API", tone: "warning" },
      { key: "blocked", label: "Bloqueados", value: "API", tone: "danger" },
    ],
    tableColumns: columns([
      "Nombre / razon social",
      "Nombre comercial",
      "RFC / Tax ID",
      "Categoria",
      "Estado",
      "Contacto principal",
      "Productos asociados",
      "Sucursales",
      "Advertencias",
    ]),
    emptyDescription:
      "No hay proveedores registrados. Crea el primer proveedor para iniciar la gestion de compras.",
    detailTitle: "Detalle de proveedor",
    auditEntityType: "supplier",
    permissionActions: ["view", "create", "update", "void", "export"],
  }),
  moduleDefinition({
    key: "purchases",
    routeSlug: "compras-entradas",
    sectionKey: "purchasesSupply",
    title: "Compras / entradas",
    description:
      "Registra compras, entradas directas, recepciones parciales e impacto en inventario.",
    status: "ready",
    actionLabel: "Nueva compra",
    filters: ["branch", "dateRange", "status", "search"],
    metrics: [
      { key: "documents", label: "Compras", value: "API", tone: "info" },
      { key: "amount", label: "Monto comprado", value: "API" },
      { key: "pending", label: "Pendientes", value: "API", tone: "warning" },
      { key: "discrepancies", label: "Discrepancias", value: "API", tone: "danger" },
    ],
    tableColumns: columns([
      "Folio",
      "Tipo",
      "Proveedor",
      "Sucursal receptora",
      "Documento externo",
      "Fecha",
      "Estado",
      "Lineas",
      "Monto",
      "Discrepancias",
    ]),
    emptyDescription: "No hay compras o entradas para los filtros seleccionados.",
    detailTitle: "Detalle de compra / entrada",
    auditEntityType: "purchase_document",
    permissionActions: ["view", "create", "update", "void", "export"],
  }),
  moduleDefinition({
    key: "suppliesConsumables",
    routeSlug: "insumos-consumibles",
    sectionKey: "purchasesSupply",
    title: "Insumos y consumibles",
    description:
      "Administra materias primas, consumibles, desechables, costos, proveedores y preparación operativa.",
    status: "ready",
    actionLabel: "Nuevo insumo",
    filters: defaultCatalogFilters,
    metrics: [
      { key: "raw-materials", label: "Materia prima", value: "API", tone: "info" },
      { key: "consumables", label: "Consumibles", value: "API", tone: "success" },
      { key: "disposables", label: "Desechables", value: "API" },
      { key: "without-supplier", label: "Sin proveedor", value: "API", tone: "warning" },
      { key: "missing-cost", label: "Sin costo", value: "API", tone: "warning" },
      { key: "low-stock", label: "Stock bajo", value: "API", tone: "danger" },
    ],
    tableColumns: columns([
      "Código",
      "Nombre",
      "Tipo",
      "Categoría / familia",
      "Unidad base",
      "Unidad de compra",
      "Costo estándar",
      "Proveedor principal",
      "Stock estado",
      "Usado en recetas",
      "Advertencias",
    ]),
    emptyDescription: "No hay insumos o consumibles registrados para los filtros seleccionados.",
    detailTitle: "Detalle de insumo",
    auditEntityType: "input_supply",
    permissionActions: ["view", "create", "update", "configure", "export"],
  }),
  moduleDefinition({
    key: "cashCuts",
    routeSlug: "cortes-caja",
    sectionKey: "cashFinance",
    title: "Cortes de caja",
    description:
      "Consulta cierres de caja, diferencias, ventas incluidas, pagos, devoluciones y contexto operativo.",
    status: "ready",
    filters: defaultFinanceFilters,
    metrics: [
      { key: "closed", label: "Cortes", value: "API", tone: "success" },
      { key: "expected-cash", label: "Efectivo esperado", value: "API", tone: "info" },
      { key: "counted-cash", label: "Efectivo contado", value: "API", tone: "info" },
      { key: "differences", label: "Con diferencia", value: "API", tone: "danger" },
      { key: "pending-close", label: "Pendientes", value: "API", tone: "warning" },
    ],
    tableColumns: columns([
      "Folio / sesion",
      "Fecha apertura",
      "Fecha cierre",
      "Sucursal",
      "Caja / estacion",
      "Cajero",
      "Inicial",
      "Efectivo esperado",
      "Efectivo contado",
      "Diferencia",
      "Ventas",
      "Metodos de pago",
      "Estado",
    ]),
    emptyDescription: "No hay cortes de caja para los filtros seleccionados.",
    detailTitle: "Detalle de corte",
    auditEntityType: "cash_close",
    permissionActions: ["view", "export"],
  }),
  moduleDefinition({
    key: "reconciliation",
    routeSlug: "conciliacion",
    sectionKey: "cashFinance",
    title: "Conciliacion",
    description:
      "Revisa diferencias de caja y medios de pago, documenta causas y resuelve discrepancias con trazabilidad.",
    status: "ready",
    actionLabel: "Nueva conciliacion",
    filters: defaultFinanceFilters,
    metrics: [
      { key: "pending", label: "Pendientes", value: "API", tone: "warning" },
      { key: "matched", label: "Conciliadas", value: "API", tone: "success" },
      { key: "variance", label: "Diferencia neta", value: "API", tone: "danger" },
      { key: "cash", label: "Efectivo", value: "API", tone: "info" },
      { key: "evidence", label: "Con evidencia", value: "API", tone: "info" },
    ],
    tableColumns: columns([
      "Folio",
      "Fecha",
      "Sucursal",
      "Caja / estacion",
      "Origen",
      "Metodo",
      "Esperado",
      "Reportado",
      "Diferencia",
      "Estado",
      "Responsable",
      "Evidencia",
      "Advertencias",
    ]),
    emptyDescription: "No hay conciliaciones para los filtros seleccionados.",
    detailTitle: "Detalle de conciliacion",
    auditEntityType: "financial_reconciliation",
    permissionActions: ["view", "update", "export"],
  }),
  moduleDefinition({
    key: "operationalPayments",
    routeSlug: "pagos-operativos",
    sectionKey: "cashFinance",
    title: "Pagos operativos",
    description:
      "Consulta salidas de caja por sucursal, concepto, usuario, fecha e impacto en corte.",
    status: "preparation",
    filters: defaultFinanceFilters,
    metrics: [
      { key: "payments", label: "Pagos", value: "Sin datos", tone: "info" },
      { key: "cash-impact", label: "Impacto efectivo", value: "Sin datos", tone: "warning" },
    ],
    tableColumns: columns([
      "Fecha",
      "Sucursal",
      "Concepto",
      "Usuario",
      "Método",
      "Monto",
      "Estado",
    ]),
    emptyDescription:
      "Aquí se consultarán salidas auditables como proveedores, servicios o logística.",
    detailTitle: "Detalle de pago",
    auditEntityType: "operational_payment",
    permissionActions: ["view", "export"],
  }),
  moduleDefinition({
    key: "cashFlow",
    routeSlug: "flujo-efectivo",
    sectionKey: "cashFinance",
    title: "Flujo de efectivo",
    description:
      "Analiza entradas, salidas, flujo neto, metodos de pago y documentos que explican el movimiento de caja.",
    status: "ready",
    filters: ["branch", "dateRange", "status", "user", "search"],
    metrics: [
      { key: "inflows", label: "Entradas", value: "API", tone: "success" },
      { key: "outflows", label: "Salidas", value: "API", tone: "warning" },
      { key: "net-flow", label: "Flujo neto", value: "API", tone: "info" },
      { key: "cash", label: "Efectivo", value: "API", tone: "success" },
      { key: "card", label: "Tarjeta", value: "API", tone: "info" },
      {
        key: "pending-reconciliation",
        label: "Pendiente conciliacion",
        value: "API",
        tone: "warning",
      },
    ],
    tableColumns: columns([
      "Fecha / hora",
      "Sucursal",
      "Caja / estacion",
      "Direccion",
      "Origen",
      "Folio origen",
      "Categoria",
      "Metodo",
      "Monto",
      "Conciliacion",
      "Operador",
      "Advertencias",
    ]),
    emptyDescription: "No hay movimientos de flujo de efectivo para los filtros seleccionados.",
    detailTitle: "Detalle de movimiento",
    auditEntityType: "cash_flow",
    permissionActions: ["view", "export"],
  }),
  moduleDefinition({
    key: "cleaningLogs",
    routeSlug: "bitacoras-limpieza",
    sectionKey: "qualityHygiene",
    title: "Bitacoras de limpieza",
    description:
      "Registra y consulta actividades de limpieza por sucursal, zona, turno, responsable, checklist y evidencia.",
    status: "partial",
    actionLabel: "Nueva bitacora",
    filters: ["branch", "dateRange", "status", "shift", "user", "search"],
    metrics: [
      { key: "total", label: "Bitacoras del periodo", value: "Sin datos", tone: "info" },
      { key: "completed", label: "Completadas", value: "Sin datos", tone: "success" },
      { key: "pending", label: "Pendientes", value: "Sin datos", tone: "warning" },
      { key: "overdue", label: "Vencidas", value: "Sin datos", tone: "danger" },
      { key: "evidence", label: "Con evidencia", value: "Sin datos", tone: "info" },
      { key: "observations", label: "Con observaciones", value: "Sin datos", tone: "warning" },
      { key: "high-risk", label: "Alto riesgo", value: "Sin datos", tone: "danger" },
      { key: "review", label: "Por revisar", value: "Sin datos", tone: "danger" },
    ],
    tableColumns: columns([
      "Folio",
      "Fecha programada",
      "Fecha realizada",
      "Sucursal",
      "Zona / area",
      "Equipo",
      "Turno",
      "Responsable",
      "Tipo de limpieza",
      "Checklist",
      "Estado",
      "Evidencia",
      "Observaciones",
      "Riesgo",
      "Acciones",
    ]),
    emptyDescription: "No hay bitacoras de limpieza para los filtros seleccionados.",
    detailTitle: "Detalle de bitacora",
    auditEntityType: "cleaning_log",
    permissionActions: ["view", "create", "update", "export"],
  }),
  moduleDefinition({
    key: "sanitaryChecks",
    routeSlug: "verificaciones-sanitarias",
    sectionKey: "qualityHygiene",
    title: "Verificaciones sanitarias",
    description:
      "Evalua el cumplimiento sanitario por sucursal, zona, equipo, proceso, checklist, evidencia y nivel de riesgo.",
    status: "partial",
    actionLabel: "Nueva verificacion",
    filters: ["branch", "dateRange", "status", "user", "search"],
    metrics: [
      { key: "total", label: "Verificaciones", value: "Backend", tone: "info" },
      { key: "passed", label: "Aprobadas", value: "Backend", tone: "success" },
      { key: "failed", label: "Fallidas", value: "Backend", tone: "danger" },
      { key: "pending", label: "Pendientes", value: "Backend", tone: "warning" },
      { key: "incident", label: "Con incidencia", value: "Backend", tone: "warning" },
      { key: "highRisk", label: "Alto riesgo", value: "Backend", tone: "danger" },
      { key: "evidence", label: "Con evidencia", value: "Backend", tone: "info" },
      { key: "followUp", label: "Por seguimiento", value: "Backend", tone: "warning" },
    ],
    tableColumns: columns([
      "Folio",
      "Fecha programada",
      "Fecha realizada",
      "Sucursal",
      "Zona / area",
      "Equipo / proceso",
      "Inspector",
      "Checklist",
      "Resultado",
      "Estado",
      "Riesgo",
      "Incidencia",
      "Evidencia",
      "Acciones",
    ]),
    emptyDescription: "No hay verificaciones sanitarias para los filtros seleccionados.",
    detailTitle: "Detalle sanitario",
    auditEntityType: "sanitary_verification",
    permissionActions: ["view", "create", "update", "export"],
  }),
  moduleDefinition({
    key: "incidents",
    routeSlug: "incidencias",
    sectionKey: "qualityHygiene",
    title: "Incidencias",
    description:
      "Registra, clasifica y da seguimiento a problemas operativos, sanitarios, de limpieza, equipo, produccion o inventario.",
    status: "partial",
    actionLabel: "Nueva incidencia",
    filters: ["branch", "dateRange", "status", "user", "search"],
    metrics: [
      { key: "total", label: "Incidencias del periodo", value: "Backend", tone: "info" },
      { key: "open", label: "Abiertas", value: "Backend", tone: "warning" },
      { key: "in-progress", label: "En seguimiento", value: "Backend", tone: "info" },
      { key: "resolved", label: "Resueltas", value: "Backend", tone: "success" },
      { key: "high-risk", label: "Alto riesgo", value: "Backend", tone: "danger" },
      { key: "overdue", label: "Vencidas", value: "Backend", tone: "danger" },
      { key: "evidence", label: "Con evidencia", value: "Backend", tone: "info" },
      { key: "sanitary", label: "Generadas por verificacion", value: "Backend", tone: "warning" },
    ],
    tableColumns: columns([
      "Folio",
      "Fecha",
      "Sucursal",
      "Zona / area",
      "Tipo",
      "Origen",
      "Severidad",
      "Estado",
      "Responsable",
      "Vencimiento",
      "Evidencia",
      "Documentos relacionados",
      "Advertencias",
      "Acciones",
    ]),
    emptyDescription: "No hay incidencias para los filtros seleccionados.",
    detailTitle: "Detalle de incidencia",
    auditEntityType: "incident",
    permissionActions: ["view", "create", "update", "export"],
  }),
  moduleDefinition({
    key: "equipmentMaintenance",
    routeSlug: "mantenimiento-equipos",
    sectionKey: "qualityHygiene",
    title: "Mantenimiento de equipos",
    description:
      "Administra equipos, servicios preventivos, fallas, reparaciones, evidencias, costos y estado operativo por sucursal.",
    status: "partial",
    actionLabel: "Nuevo equipo",
    filters: ["branch", "dateRange", "status", "search"],
    metrics: [
      { key: "equipment", label: "Equipos registrados", value: "Backend", tone: "info" },
      { key: "operational", label: "Operativos", value: "Backend", tone: "success" },
      { key: "out-of-service", label: "Fuera de servicio", value: "Backend", tone: "danger" },
      { key: "pending", label: "Mantenimientos pendientes", value: "Backend", tone: "warning" },
      { key: "overdue", label: "Vencidos", value: "Backend", tone: "danger" },
      { key: "corrective", label: "Correctivos abiertos", value: "Backend", tone: "warning" },
      { key: "high-risk", label: "Alto riesgo", value: "Backend", tone: "danger" },
      { key: "cost", label: "Costo del periodo", value: "Backend", tone: "info" },
    ],
    tableColumns: columns([
      "Codigo / activo",
      "Equipo",
      "Tipo",
      "Sucursal",
      "Zona / area",
      "Estado operativo",
      "Ultimo mantenimiento",
      "Proximo mantenimiento",
      "Mantenimiento estado",
      "Riesgo",
      "Incidencias",
      "Costo periodo",
    ]),
    emptyDescription: "No hay equipos registrados para los filtros seleccionados.",
    detailTitle: "Detalle de equipo",
    auditEntityType: "equipment_asset",
    permissionActions: ["view", "create", "update", "configure", "export"],
  }),
  moduleDefinition({
    key: "users",
    routeSlug: "usuarios",
    sectionKey: "control",
    title: "Usuarios",
    description:
      "Administra usuarios, acceso a POS y Backoffice, sucursales asignadas, roles y estado de cuenta.",
    status: "partial",
    actionLabel: "Nuevo usuario",
    filters: ["branch", "status", "user", "search"],
    metrics: [
      { key: "total", label: "Usuarios totales", value: "Backend", tone: "info" },
      { key: "active", label: "Activos", value: "Backend", tone: "success" },
      { key: "inactive", label: "Inactivos", value: "Backend", tone: "warning" },
      { key: "locked", label: "Bloqueados", value: "Backend", tone: "danger" },
      { key: "pending", label: "Pendientes", value: "No soportado", tone: "default" },
      { key: "pos", label: "POS", value: "Backend", tone: "info" },
      { key: "backoffice", label: "Backoffice", value: "Backend", tone: "info" },
      { key: "without-branch", label: "Sin sucursal", value: "Backend", tone: "warning" },
    ],
    tableColumns: columns([
      "Nombre",
      "Correo",
      "Estado",
      "Acceso",
      "Sucursales",
      "Roles",
      "Último acceso",
      "Creado",
      "Advertencias",
      "Acciones",
    ]),
    emptyDescription: "No hay usuarios registrados para los filtros seleccionados.",
    detailTitle: "Detalle de usuario",
    auditEntityType: "user",
    permissionActions: ["view", "create", "update", "configure", "export"],
  }),
  moduleDefinition({
    key: "rolesPermissions",
    routeSlug: "roles-permisos",
    sectionKey: "control",
    title: "Roles y permisos",
    description:
      "Define roles, permisos por modulo, acceso a POS y Backoffice, alcance operativo y usuarios asignados.",
    status: "partial",
    actionLabel: "Nuevo rol",
    filters: ["status", "search"],
    metrics: [
      { key: "total", label: "Roles totales", value: "Backend", tone: "info" },
      { key: "active", label: "Activos", value: "Backend", tone: "success" },
      { key: "inactive", label: "Inactivos", value: "Backend", tone: "warning" },
      { key: "with-users", label: "Con usuarios", value: "Backend", tone: "info" },
      { key: "without-users", label: "Sin usuarios", value: "Backend", tone: "warning" },
      { key: "high-privilege", label: "Alto privilegio", value: "Backend", tone: "danger" },
      { key: "pos", label: "POS", value: "Backend", tone: "info" },
      { key: "backoffice", label: "Backoffice", value: "Backend", tone: "info" },
      { key: "warnings", label: "Con advertencias", value: "Backend", tone: "warning" },
    ],
    tableColumns: columns([
      "Rol",
      "Descripcion",
      "Estado",
      "Acceso",
      "Permisos",
      "Usuarios asignados",
      "Alcance",
      "Riesgo",
      "Ultima actualizacion",
      "Advertencias",
      "Acciones",
    ]),
    emptyDescription: "No hay roles registrados para los filtros seleccionados.",
    detailTitle: "Detalle de rol",
    auditEntityType: "role",
    permissionActions: ["view", "create", "update", "configure", "export"],
  }),
  moduleDefinition({
    key: "audit",
    routeSlug: "auditoria",
    sectionKey: "control",
    title: "Auditoria",
    description:
      "Consulta acciones sensibles, cambios de datos, eventos de seguridad y trazabilidad operativa.",
    status: "partial",
    filters: ["branch", "dateRange", "status", "user", "search"],
    metrics: [
      { key: "events", label: "Eventos del periodo", value: "Backend", tone: "info" },
      { key: "sensitive", label: "Acciones sensibles", value: "Backend", tone: "warning" },
      { key: "financial", label: "Cambios financieros", value: "Backend", tone: "warning" },
      { key: "inventory", label: "Cambios inventario", value: "Backend", tone: "info" },
      { key: "access", label: "Cambios de acceso", value: "Backend", tone: "danger" },
      { key: "failed", label: "Fallidos / bloqueados", value: "Backend", tone: "danger" },
      { key: "system", label: "Sistema", value: "Backend", tone: "info" },
    ],
    tableColumns: columns([
      "Fecha / hora",
      "Usuario / actor",
      "Origen",
      "Modulo",
      "Accion",
      "Entidad",
      "Documento",
      "Resultado",
      "Sensible",
      "Sucursal",
      "Estacion",
      "Severidad",
      "Acciones",
    ]),
    emptyDescription: "No hay eventos de auditoria para los filtros seleccionados.",
    detailTitle: "Detalle de auditoria",
    auditEntityType: "audit_event",
    permissionActions: ["view", "export"],
  }),
  moduleDefinition({
    key: "reports",
    routeSlug: "reportes",
    sectionKey: "control",
    title: "Reportes",
    description: "Consulta y exporta reportes operativos, financieros, inventario, calidad y control.",
    status: "partial",
    filters: ["search", "status", "dateRange", "branch"],
    metrics: [
      { key: "available", label: "Reportes disponibles", value: "Backend", tone: "success" },
      { key: "categories", label: "Categorias", value: "Backend", tone: "info" },
      { key: "exportable", label: "Exportables", value: "Backend", tone: "info" },
      { key: "sensitive", label: "Sensibles", value: "Backend", tone: "warning" },
      { key: "pending", label: "Pendientes backend", value: "Backend", tone: "warning" },
    ],
    tableColumns: columns([
      "Reporte",
      "Categoria",
      "Fuentes",
      "Filtros",
      "Estado",
      "Exportacion",
      "Sensibilidad",
      "Acciones",
    ]),
    emptyDescription:
      "No hay reportes que coincidan con los filtros seleccionados.",
    detailTitle: "Detalle de reporte",
    auditEntityType: "report",
    permissionActions: ["view", "export"],
  }),
  moduleDefinition({
    key: "settings",
    routeSlug: "configuracion",
    sectionKey: "control",
    title: "Configuración",
    description:
      "Define reglas globales, comportamiento operativo, POS, caja, inventario, pedidos y notificaciones.",
    status: "partial",
    filters: ["status", "search"],
    metrics: [
      { key: "active", label: "Configuraciones activas", value: "Backend", tone: "info" },
      { key: "warnings", label: "Con advertencias", value: "Backend", tone: "warning" },
      { key: "pending", label: "Pendientes", value: "Backend", tone: "warning" },
      { key: "recent", label: "Cambios recientes", value: "Backend", tone: "info" },
      { key: "sensitive", label: "Sensibles", value: "Backend", tone: "warning" },
      { key: "scoped", label: "Por sucursal", value: "Backend", tone: "info" },
      { key: "integrations", label: "Integraciones", value: "Backend", tone: "info" },
    ],
    tableColumns: columns([
      "Configuracion",
      "Categoria",
      "Valor",
      "Alcance",
      "Modulos",
      "Advertencias",
      "Acciones",
    ]),
    emptyDescription:
      "No hay configuraciones que coincidan con los filtros seleccionados.",
    detailTitle: "Detalle de configuracion",
    auditEntityType: "system_setting",
    permissionActions: ["view", "update", "configure", "export"],
  }),
];

export const adminModuleByKey = new Map<AdminModuleKey, AdminModuleDefinition>(
  adminModules.map((module) => [module.key, module]),
);

export function getAdminModule(moduleKey: AdminModuleKey): AdminModuleDefinition {
  const module = adminModuleByKey.get(moduleKey);
  if (!module) {
    throw new Error(`Unknown admin module: ${moduleKey}`);
  }

  return module;
}

export function getAdminModulesBySection(sectionKey: AdminSectionKey): AdminModuleDefinition[] {
  return adminModules.filter((module) => module.sectionKey === sectionKey);
}

export const adminRoutePaths = ["/admin", ...adminModules.map((module) => module.path)] as const;
