IDENTITY_SURFACE_POS = "POS"
IDENTITY_SURFACE_BACKOFFICE = "BACKOFFICE"

IDENTITY_ALLOWED_SURFACES = (IDENTITY_SURFACE_POS, IDENTITY_SURFACE_BACKOFFICE)

IDENTITY_ROLE_ADMIN = "admin"
IDENTITY_ROLE_CASHIER = "cashier"
IDENTITY_ROLE_BRANCH_MANAGER = "branch_manager"
