line-length = 160
target-version = "py312"

[lint]
# Conjunto de reglas útiles:
select = ["E", "F", "I", "B", "UP"]
# E,F: pycodestyle/pyflakes; I: isort (ordenar imports); B: bugbear; UP: pyupgrade

# Si algo te molesta, lo agregas aquí:
ignore = []

[format]
# Ruff NO hará el formateo (lo hace Black), pero esta sección no molesta.
quote-style = "double"
