OPERATION_DOCUMENT_TYPE_COUNTER_TRANSFER = "COUNTER_TRANSFER"
OPERATION_DOCUMENT_TYPE_WASTE_RECORD = "WASTE_RECORD"
OPERATION_DOCUMENT_TYPE_BRANCH_TRANSFER_SHIPMENT = "BRANCH_TRANSFER_SHIPMENT"
OPERATION_DOCUMENT_TYPE_BRANCH_TRANSFER_RECEIPT = "BRANCH_TRANSFER_RECEIPT"
OPERATION_DOCUMENT_TYPE_CLOSE_COUNTER_ADJUSTMENT = "CLOSE_COUNTER_ADJUSTMENT"
OPERATION_DOCUMENT_TYPE_CLOSE_WASTE_ADJUSTMENT = "CLOSE_WASTE_ADJUSTMENT"

OPERATION_DOCUMENT_STATUS_DRAFT = "DRAFT"
OPERATION_DOCUMENT_STATUS_COMMITTED = "COMMITTED"
OPERATION_DOCUMENT_STATUS_IN_TRANSIT = "IN_TRANSIT"
OPERATION_DOCUMENT_STATUS_RECEIVED = "RECEIVED"
OPERATION_DOCUMENT_STATUS_RECEIVED_WITH_VARIANCE = "RECEIVED_WITH_VARIANCE"
OPERATION_DOCUMENT_STATUS_CANCELLED = "CANCELLED"

OPERATION_BUCKET_BACKROOM = "BACKROOM"
OPERATION_BUCKET_COUNTER = "COUNTER"
OPERATION_BUCKET_IN_TRANSIT = "IN_TRANSIT"
OPERATION_BUCKET_WASTE = "WASTE"

OPERATION_UNIT_OF_MEASURE_EACH = "EACH"

OPERATION_MODULE_COUNTER_TRANSFER = OPERATION_DOCUMENT_TYPE_COUNTER_TRANSFER
OPERATION_MODULE_WASTE_RECORD = OPERATION_DOCUMENT_TYPE_WASTE_RECORD
OPERATION_MODULE_BRANCH_TRANSFER_SHIPMENT = OPERATION_DOCUMENT_TYPE_BRANCH_TRANSFER_SHIPMENT
OPERATION_MODULE_BRANCH_TRANSFER_RECEIPT = OPERATION_DOCUMENT_TYPE_BRANCH_TRANSFER_RECEIPT

OPERATION_HISTORY_SCOPE_CURRENT_SHIFT = "CURRENT_SHIFT"
OPERATION_HISTORY_SCOPE_ALL = "ALL"
OPERATION_HISTORY_SCOPE_TODAY = "TODAY"
OPERATION_HISTORY_SCOPE_RECENT = "RECENT"

WASTE_REASON_OLD_COUNTER = "OLD_COUNTER"
WASTE_REASON_DAMAGED = "DAMAGED"
WASTE_REASON_CONTAMINATED = "CONTAMINATED"
WASTE_REASON_EXPIRED = "EXPIRED"
WASTE_REASON_OTHER = "OTHER"

OUTBOX_EVENT_COUNTER_TRANSFER_COMMITTED_V1 = "counter_transfer.committed.v1"
OUTBOX_EVENT_WASTE_RECORD_COMMITTED_V1 = "waste_record.committed.v1"
OUTBOX_EVENT_WASTE_RECORD_HIGH_IMPACT_ALERT_V1 = "waste_record.high_impact_alert.v1"
OUTBOX_EVENT_TRANSFER_DISPATCHED_V1 = "transfer.dispatched.v1"
OUTBOX_EVENT_TRANSFER_RECEIVED_V1 = "transfer.received.v1"

BRANCH_BRAND_EL_MEJOR_PAN = "EL_MEJOR_PAN"
BRANCH_BRAND_MERENNA = "MERENNA"

VALID_OPERATION_DOCUMENT_TYPES = {
    OPERATION_DOCUMENT_TYPE_COUNTER_TRANSFER,
    OPERATION_DOCUMENT_TYPE_WASTE_RECORD,
    OPERATION_DOCUMENT_TYPE_BRANCH_TRANSFER_SHIPMENT,
    OPERATION_DOCUMENT_TYPE_BRANCH_TRANSFER_RECEIPT,
    OPERATION_DOCUMENT_TYPE_CLOSE_COUNTER_ADJUSTMENT,
    OPERATION_DOCUMENT_TYPE_CLOSE_WASTE_ADJUSTMENT,
}

VALID_OPERATION_DOCUMENT_STATUSES = {
    OPERATION_DOCUMENT_STATUS_DRAFT,
    OPERATION_DOCUMENT_STATUS_COMMITTED,
    OPERATION_DOCUMENT_STATUS_IN_TRANSIT,
    OPERATION_DOCUMENT_STATUS_RECEIVED,
    OPERATION_DOCUMENT_STATUS_RECEIVED_WITH_VARIANCE,
    OPERATION_DOCUMENT_STATUS_CANCELLED,
}

VALID_OPERATION_BUCKET_CODES = {
    OPERATION_BUCKET_BACKROOM,
    OPERATION_BUCKET_COUNTER,
    OPERATION_BUCKET_IN_TRANSIT,
    OPERATION_BUCKET_WASTE,
}

VALID_OPERATION_MODULES = {
    OPERATION_MODULE_COUNTER_TRANSFER,
    OPERATION_MODULE_WASTE_RECORD,
    OPERATION_MODULE_BRANCH_TRANSFER_SHIPMENT,
    OPERATION_MODULE_BRANCH_TRANSFER_RECEIPT,
}

VALID_OPERATION_HISTORY_SCOPES = {
    OPERATION_HISTORY_SCOPE_ALL,
    OPERATION_HISTORY_SCOPE_CURRENT_SHIFT,
    OPERATION_HISTORY_SCOPE_TODAY,
    OPERATION_HISTORY_SCOPE_RECENT,
}

WASTE_REASON_CODES_REQUIRING_NOTE = {
    WASTE_REASON_DAMAGED,
    WASTE_REASON_CONTAMINATED,
    WASTE_REASON_OTHER,
}

WASTE_STOCK_VALIDATED_SOURCE_BUCKET_CODES = {
    OPERATION_BUCKET_COUNTER,
}

BRANCH_BRAND_MAPPING = {
    "MAIN": BRANCH_BRAND_EL_MEJOR_PAN,
    "NORTE": BRANCH_BRAND_MERENNA,
}
