from __future__ import annotations

from decimal import Decimal

CASH_CLOSE_STATUS_PREVIEW = "PREVIEW"
CASH_CLOSE_STATUS_READY = "READY"
CASH_CLOSE_STATUS_COMMITTED = "COMMITTED"

CASH_CLOSE_RECONCILIATION_STATUS_NOT_EVALUATED = "NOT_EVALUATED"
CASH_CLOSE_RECONCILIATION_STATUS_PENDING = "PENDING"
CASH_CLOSE_RECONCILIATION_STATUS_BLOCKED = "BLOCKED"
CASH_CLOSE_RECONCILIATION_STATUS_READY = "READY"

BRANCH_COUNTER_SNAPSHOT_TYPE_CLOSE_BASELINE = "CLOSE_BASELINE"

CASH_CLOSE_BLOCKER_NO_ACTIVE_OPEN_CASH_SESSION = "NO_ACTIVE_OPEN_CASH_SESSION"
CASH_CLOSE_BLOCKER_SESSION_ALREADY_CLOSED = "SESSION_ALREADY_CLOSED"
CASH_CLOSE_BLOCKER_MISSING_COUNTER_BASELINE = "MISSING_COUNTER_BASELINE"
CASH_CLOSE_BLOCKER_INCONSISTENT_SESSION_CONTEXT = "INCONSISTENT_SESSION_CONTEXT"
CASH_CLOSE_BLOCKER_MISSING_COUNTED_PAYMENT_TOTALS = "MISSING_COUNTED_PAYMENT_TOTALS"
CASH_CLOSE_BLOCKER_MISSING_COUNTED_CLOSING_STOCK = "MISSING_COUNTED_CLOSING_STOCK"
CASH_CLOSE_BLOCKER_UNRESOLVED_CLASS_CAPTURE_MISMATCH = "UNRESOLVED_CLASS_CAPTURE_MISMATCH"
CASH_CLOSE_BLOCKER_INVALID_MANUAL_RECONCILIATION_OVERRIDE = (
    "INVALID_MANUAL_RECONCILIATION_OVERRIDE"
)
CASH_CLOSE_BLOCKER_INVALID_DISCREPANCY_RESOLUTION = "INVALID_DISCREPANCY_RESOLUTION"
CASH_CLOSE_BLOCKER_INTERNAL_INTEGRITY_MISMATCH = "INTERNAL_INTEGRITY_MISMATCH"

CASH_CLOSE_WARNING_PENDING_INBOUND_TRANSFERS = "PENDING_INBOUND_TRANSFERS"
CASH_CLOSE_WARNING_OUTBOUND_TRANSFERS_IN_TRANSIT = "OUTBOUND_TRANSFERS_IN_TRANSIT"
CASH_CLOSE_WARNING_LARGE_CASH_VARIANCE = "LARGE_CASH_VARIANCE"
CASH_CLOSE_WARNING_LONG_SESSION_DURATION = "LONG_SESSION_DURATION"

CASH_CLOSE_CURRENCY_MXN = "MXN"

CASH_CLOSE_PAYMENT_METHOD_CASH = "CASH"
CASH_CLOSE_PAYMENT_METHOD_CARD = "CARD"
CASH_CLOSE_PAYMENT_METHOD_MIXED = "MIXED"

CASH_CLOSE_CLASS_RESOLUTION_STATUS_COUNT_REQUIRED = "COUNT_REQUIRED"
CASH_CLOSE_CLASS_RESOLUTION_STATUS_AUTO_RESOLVED = "AUTO_RESOLVED"
CASH_CLOSE_CLASS_RESOLUTION_STATUS_MANUAL_RESOLVED = "MANUAL_RESOLVED"
CASH_CLOSE_CLASS_RESOLUTION_STATUS_UNRESOLVED = "UNRESOLVED"

CASH_CLOSE_DISCREPANCY_REASON_COUNT_ERROR = "COUNT_ERROR"
CASH_CLOSE_DISCREPANCY_REASON_UNREGISTERED_WASTE = "UNREGISTERED_WASTE"
CASH_CLOSE_DISCREPANCY_REASON_UNREGISTERED_PASS_TO_COUNTER = "UNREGISTERED_PASS_TO_COUNTER"
CASH_CLOSE_DISCREPANCY_REASON_COUNTER_SHORTAGE = "COUNTER_SHORTAGE"
CASH_CLOSE_DISCREPANCY_REASON_COUNTER_OVERAGE = "COUNTER_OVERAGE"
CASH_CLOSE_DISCREPANCY_REASON_OTHER = "OTHER"

CASH_CLOSE_DISCREPANCY_RESOLUTION_TYPE_CLOSE_COUNTER_ADJUSTMENT = "CLOSE_COUNTER_ADJUSTMENT"
CASH_CLOSE_DISCREPANCY_RESOLUTION_TYPE_CLOSE_WASTE_ADJUSTMENT = "CLOSE_WASTE_ADJUSTMENT"

CASH_CLOSE_ISSUE_LEVEL_BLOCKER = "BLOCKER"
CASH_CLOSE_ISSUE_LEVEL_WARNING = "WARNING"

OUTBOX_EVENT_CASH_SESSION_CLOSED_V1 = "cash_session.closed.v1"
OUTBOX_EVENT_CLASS_CAPTURE_RECONCILED_V1 = "class_capture.reconciled.v1"
OUTBOX_EVENT_CLOSE_DISCREPANCY_GENERATED_V1 = "close_discrepancy.generated.v1"

LARGE_CASH_VARIANCE_WARNING_THRESHOLD = Decimal("100.00")
LONG_SESSION_DURATION_WARNING_HOURS = 8

VALID_CASH_CLOSE_STATUSES = {
    CASH_CLOSE_STATUS_PREVIEW,
    CASH_CLOSE_STATUS_READY,
    CASH_CLOSE_STATUS_COMMITTED,
}

VALID_CASH_CLOSE_RECONCILIATION_STATUSES = {
    CASH_CLOSE_RECONCILIATION_STATUS_NOT_EVALUATED,
    CASH_CLOSE_RECONCILIATION_STATUS_PENDING,
    CASH_CLOSE_RECONCILIATION_STATUS_BLOCKED,
    CASH_CLOSE_RECONCILIATION_STATUS_READY,
}

VALID_BRANCH_COUNTER_SNAPSHOT_TYPES = {
    BRANCH_COUNTER_SNAPSHOT_TYPE_CLOSE_BASELINE,
}

VALID_CASH_CLOSE_PAYMENT_METHOD_CODES = {
    CASH_CLOSE_PAYMENT_METHOD_CASH,
    CASH_CLOSE_PAYMENT_METHOD_CARD,
    CASH_CLOSE_PAYMENT_METHOD_MIXED,
}

EXPECTED_CASH_CLOSE_PAYMENT_METHOD_CODES = {
    CASH_CLOSE_PAYMENT_METHOD_CASH,
}

VALID_CASH_CLOSE_CLASS_RESOLUTION_STATUSES = {
    CASH_CLOSE_CLASS_RESOLUTION_STATUS_COUNT_REQUIRED,
    CASH_CLOSE_CLASS_RESOLUTION_STATUS_AUTO_RESOLVED,
    CASH_CLOSE_CLASS_RESOLUTION_STATUS_MANUAL_RESOLVED,
    CASH_CLOSE_CLASS_RESOLUTION_STATUS_UNRESOLVED,
}

VALID_CASH_CLOSE_DISCREPANCY_REASON_CODES = {
    CASH_CLOSE_DISCREPANCY_REASON_COUNT_ERROR,
    CASH_CLOSE_DISCREPANCY_REASON_UNREGISTERED_WASTE,
    CASH_CLOSE_DISCREPANCY_REASON_UNREGISTERED_PASS_TO_COUNTER,
    CASH_CLOSE_DISCREPANCY_REASON_COUNTER_SHORTAGE,
    CASH_CLOSE_DISCREPANCY_REASON_COUNTER_OVERAGE,
    CASH_CLOSE_DISCREPANCY_REASON_OTHER,
}

VALID_CASH_CLOSE_DISCREPANCY_RESOLUTION_TYPES = {
    CASH_CLOSE_DISCREPANCY_RESOLUTION_TYPE_CLOSE_COUNTER_ADJUSTMENT,
    CASH_CLOSE_DISCREPANCY_RESOLUTION_TYPE_CLOSE_WASTE_ADJUSTMENT,
}

VALID_CASH_CLOSE_ISSUE_LEVELS = {
    CASH_CLOSE_ISSUE_LEVEL_BLOCKER,
    CASH_CLOSE_ISSUE_LEVEL_WARNING,
}
