from __future__ import annotations

from decimal import Decimal

CASH_CLOSE_STATUS_PREVIEW = "PREVIEW"
CASH_CLOSE_STATUS_READY = "READY"
CASH_CLOSE_STATUS_COMMITTED = "COMMITTED"

CASH_CLOSE_MODE_WITH_COUNT = "WITH_COUNT"

CASH_CLOSE_RECONCILIATION_STATUS_NOT_EVALUATED = "NOT_EVALUATED"
CASH_CLOSE_RECONCILIATION_STATUS_PENDING = "PENDING"
CASH_CLOSE_RECONCILIATION_STATUS_BLOCKED = "BLOCKED"
CASH_CLOSE_RECONCILIATION_STATUS_READY = "READY"

BRANCH_COUNTER_SNAPSHOT_TYPE_CLOSE_BASELINE = "CLOSE_BASELINE"

CASH_CLOSE_BLOCKER_NO_ACTIVE_OPEN_CASH_SESSION = "NO_ACTIVE_OPEN_CASH_SESSION"
CASH_CLOSE_BLOCKER_SESSION_ALREADY_CLOSED = "SESSION_ALREADY_CLOSED"
CASH_CLOSE_BLOCKER_MISSING_COUNTER_BASELINE = "MISSING_COUNTER_BASELINE"
CASH_CLOSE_BLOCKER_INCONSISTENT_SESSION_CONTEXT = "INCONSISTENT_SESSION_CONTEXT"
CASH_CLOSE_BLOCKER_MISSING_COUNTED_PAYMENT_TOTALS = "MISSING_COUNTED_PAYMENT_TOTALS"
CASH_CLOSE_BLOCKER_MISSING_COUNTED_CLOSING_STOCK = "MISSING_COUNTED_CLOSING_STOCK"
CASH_CLOSE_BLOCKER_UNRESOLVED_CLASS_CAPTURE_MISMATCH = "UNRESOLVED_CLASS_CAPTURE_MISMATCH"
CASH_CLOSE_BLOCKER_INVALID_MANUAL_RECONCILIATION_OVERRIDE = "INVALID_MANUAL_RECONCILIATION_OVERRIDE"
CASH_CLOSE_BLOCKER_INVALID_DISCREPANCY_RESOLUTION = "INVALID_DISCREPANCY_RESOLUTION"
CASH_CLOSE_BLOCKER_INVALID_COUNT_PAYLOAD = "INVALID_COUNT_PAYLOAD"
CASH_CLOSE_BLOCKER_INTERNAL_INTEGRITY_MISMATCH = "INTERNAL_INTEGRITY_MISMATCH"

CASH_CLOSE_WARNING_PENDING_INBOUND_TRANSFERS = "PENDING_INBOUND_TRANSFERS"
CASH_CLOSE_WARNING_OUTBOUND_TRANSFERS_IN_TRANSIT = "OUTBOUND_TRANSFERS_IN_TRANSIT"
CASH_CLOSE_WARNING_LARGE_CASH_VARIANCE = "LARGE_CASH_VARIANCE"
CASH_CLOSE_WARNING_LONG_SESSION_DURATION = "LONG_SESSION_DURATION"

CASH_CLOSE_CURRENCY_MXN = "MXN"

CASH_CLOSE_PAYMENT_METHOD_CASH = "CASH"
CASH_CLOSE_PAYMENT_METHOD_CARD = "CARD"
CASH_CLOSE_PAYMENT_METHOD_MIXED = "MIXED"

CASH_CLOSE_CLASS_RESOLUTION_STATUS_COUNT_REQUIRED = "COUNT_REQUIRED"
CASH_CLOSE_CLASS_RESOLUTION_STATUS_AUTO_RESOLVED = "AUTO_RESOLVED"
CASH_CLOSE_CLASS_RESOLUTION_STATUS_MANUAL_RESOLVED = "MANUAL_RESOLVED"
CASH_CLOSE_CLASS_RESOLUTION_STATUS_UNRESOLVED = "UNRESOLVED"

CASH_CLOSE_DISCREPANCY_REASON_COUNT_ERROR = "COUNT_ERROR"
CASH_CLOSE_DISCREPANCY_REASON_UNREGISTERED_WASTE = "UNREGISTERED_WASTE"
CASH_CLOSE_DISCREPANCY_REASON_UNREGISTERED_PASS_TO_COUNTER = "UNREGISTERED_PASS_TO_COUNTER"
CASH_CLOSE_DISCREPANCY_REASON_COUNTER_SHORTAGE = "COUNTER_SHORTAGE"
CASH_CLOSE_DISCREPANCY_REASON_COUNTER_OVERAGE = "COUNTER_OVERAGE"
CASH_CLOSE_DISCREPANCY_REASON_OTHER = "OTHER"

CASH_CLOSE_DISCREPANCY_RESOLUTION_TYPE_CLOSE_COUNTER_ADJUSTMENT = "CLOSE_COUNTER_ADJUSTMENT"
CASH_CLOSE_DISCREPANCY_RESOLUTION_TYPE_CLOSE_WASTE_ADJUSTMENT = "CLOSE_WASTE_ADJUSTMENT"

CASH_CLOSE_ISSUE_LEVEL_BLOCKER = "BLOCKER"
CASH_CLOSE_ISSUE_LEVEL_WARNING = "WARNING"

OUTBOX_EVENT_CASH_SESSION_CLOSED_V1 = "cash_session.closed.v1"
OUTBOX_EVENT_CLASS_CAPTURE_RECONCILED_V1 = "class_capture.reconciled.v1"
OUTBOX_EVENT_CLOSE_DISCREPANCY_GENERATED_V1 = "close_discrepancy.generated.v1"
OUTBOX_EVENT_FINANCIAL_RECONCILIATION_CREATED_V1 = "financial_reconciliation.created.v1"
OUTBOX_EVENT_FINANCIAL_RECONCILIATION_RESOLVED_V1 = "financial_reconciliation.resolved.v1"

FINANCIAL_RECONCILIATION_STATUS_PENDING = "PENDING"
FINANCIAL_RECONCILIATION_STATUS_IN_REVIEW = "IN_REVIEW"
FINANCIAL_RECONCILIATION_STATUS_RECONCILED = "RECONCILED"
FINANCIAL_RECONCILIATION_STATUS_VOIDED = "VOIDED"

FINANCIAL_RECONCILIATION_SOURCE_CASH_CUT = "CASH_CUT"
FINANCIAL_RECONCILIATION_SOURCE_PAYMENT_SETTLEMENT = "PAYMENT_SETTLEMENT"
FINANCIAL_RECONCILIATION_SOURCE_DEPOSIT = "DEPOSIT"
FINANCIAL_RECONCILIATION_SOURCE_RETURN_REFUND = "RETURN_REFUND"
FINANCIAL_RECONCILIATION_SOURCE_OPERATIONAL_PAYMENT = "OPERATIONAL_PAYMENT"
FINANCIAL_RECONCILIATION_SOURCE_CORRECTION = "CORRECTION"

FINANCIAL_RECONCILIATION_REASON_COUNTING_ERROR = "COUNTING_ERROR"
FINANCIAL_RECONCILIATION_REASON_CASH_MISSING = "CASH_MISSING"
FINANCIAL_RECONCILIATION_REASON_CASH_OVER = "CASH_OVER"
FINANCIAL_RECONCILIATION_REASON_CARD_SETTLEMENT_DIFFERENCE = "CARD_SETTLEMENT_DIFFERENCE"
FINANCIAL_RECONCILIATION_REASON_REFUND_RECORDED = "REFUND_RECORDED"
FINANCIAL_RECONCILIATION_REASON_OPERATIONAL_PAYMENT_MISSING = "OPERATIONAL_PAYMENT_MISSING"
FINANCIAL_RECONCILIATION_REASON_DEPOSIT_DIFFERENCE = "DEPOSIT_DIFFERENCE"
FINANCIAL_RECONCILIATION_REASON_DUPLICATE_TICKET = "DUPLICATE_TICKET"
FINANCIAL_RECONCILIATION_REASON_CORRECTION_APPLIED = "CORRECTION_APPLIED"
FINANCIAL_RECONCILIATION_REASON_OTHER = "OTHER"

LARGE_CASH_VARIANCE_WARNING_THRESHOLD = Decimal("100.00")
LONG_SESSION_DURATION_WARNING_HOURS = 8

VALID_CASH_CLOSE_STATUSES = {
    CASH_CLOSE_STATUS_PREVIEW,
    CASH_CLOSE_STATUS_READY,
    CASH_CLOSE_STATUS_COMMITTED,
}

VALID_CASH_CLOSE_MODES = {
    CASH_CLOSE_MODE_WITH_COUNT,
}

VALID_CASH_CLOSE_RECONCILIATION_STATUSES = {
    CASH_CLOSE_RECONCILIATION_STATUS_NOT_EVALUATED,
    CASH_CLOSE_RECONCILIATION_STATUS_PENDING,
    CASH_CLOSE_RECONCILIATION_STATUS_BLOCKED,
    CASH_CLOSE_RECONCILIATION_STATUS_READY,
}

VALID_BRANCH_COUNTER_SNAPSHOT_TYPES = {
    BRANCH_COUNTER_SNAPSHOT_TYPE_CLOSE_BASELINE,
}

VALID_CASH_CLOSE_PAYMENT_METHOD_CODES = {
    CASH_CLOSE_PAYMENT_METHOD_CASH,
    CASH_CLOSE_PAYMENT_METHOD_CARD,
    CASH_CLOSE_PAYMENT_METHOD_MIXED,
}

EXPECTED_CASH_CLOSE_PAYMENT_METHOD_CODES = {
    CASH_CLOSE_PAYMENT_METHOD_CASH,
}

VALID_CASH_CLOSE_CLASS_RESOLUTION_STATUSES = {
    CASH_CLOSE_CLASS_RESOLUTION_STATUS_COUNT_REQUIRED,
    CASH_CLOSE_CLASS_RESOLUTION_STATUS_AUTO_RESOLVED,
    CASH_CLOSE_CLASS_RESOLUTION_STATUS_MANUAL_RESOLVED,
    CASH_CLOSE_CLASS_RESOLUTION_STATUS_UNRESOLVED,
}

VALID_CASH_CLOSE_DISCREPANCY_REASON_CODES = {
    CASH_CLOSE_DISCREPANCY_REASON_COUNT_ERROR,
    CASH_CLOSE_DISCREPANCY_REASON_UNREGISTERED_WASTE,
    CASH_CLOSE_DISCREPANCY_REASON_UNREGISTERED_PASS_TO_COUNTER,
    CASH_CLOSE_DISCREPANCY_REASON_COUNTER_SHORTAGE,
    CASH_CLOSE_DISCREPANCY_REASON_COUNTER_OVERAGE,
    CASH_CLOSE_DISCREPANCY_REASON_OTHER,
}

VALID_CASH_CLOSE_DISCREPANCY_RESOLUTION_TYPES = {
    CASH_CLOSE_DISCREPANCY_RESOLUTION_TYPE_CLOSE_COUNTER_ADJUSTMENT,
    CASH_CLOSE_DISCREPANCY_RESOLUTION_TYPE_CLOSE_WASTE_ADJUSTMENT,
}

VALID_CASH_CLOSE_ISSUE_LEVELS = {
    CASH_CLOSE_ISSUE_LEVEL_BLOCKER,
    CASH_CLOSE_ISSUE_LEVEL_WARNING,
}

VALID_FINANCIAL_RECONCILIATION_STATUSES = {
    FINANCIAL_RECONCILIATION_STATUS_PENDING,
    FINANCIAL_RECONCILIATION_STATUS_IN_REVIEW,
    FINANCIAL_RECONCILIATION_STATUS_RECONCILED,
    FINANCIAL_RECONCILIATION_STATUS_VOIDED,
}

VALID_FINANCIAL_RECONCILIATION_SOURCES = {
    FINANCIAL_RECONCILIATION_SOURCE_CASH_CUT,
    FINANCIAL_RECONCILIATION_SOURCE_PAYMENT_SETTLEMENT,
    FINANCIAL_RECONCILIATION_SOURCE_DEPOSIT,
    FINANCIAL_RECONCILIATION_SOURCE_RETURN_REFUND,
    FINANCIAL_RECONCILIATION_SOURCE_OPERATIONAL_PAYMENT,
    FINANCIAL_RECONCILIATION_SOURCE_CORRECTION,
}

VALID_FINANCIAL_RECONCILIATION_REASONS = {
    FINANCIAL_RECONCILIATION_REASON_COUNTING_ERROR,
    FINANCIAL_RECONCILIATION_REASON_CASH_MISSING,
    FINANCIAL_RECONCILIATION_REASON_CASH_OVER,
    FINANCIAL_RECONCILIATION_REASON_CARD_SETTLEMENT_DIFFERENCE,
    FINANCIAL_RECONCILIATION_REASON_REFUND_RECORDED,
    FINANCIAL_RECONCILIATION_REASON_OPERATIONAL_PAYMENT_MISSING,
    FINANCIAL_RECONCILIATION_REASON_DEPOSIT_DIFFERENCE,
    FINANCIAL_RECONCILIATION_REASON_DUPLICATE_TICKET,
    FINANCIAL_RECONCILIATION_REASON_CORRECTION_APPLIED,
    FINANCIAL_RECONCILIATION_REASON_OTHER,
}
