ADMIN_WASTE_RESOURCE_TYPE = "operation_document"
ADMIN_WASTE_SOURCE_DOCUMENT_TYPE = "WASTE_RECORD"

ADMIN_WASTE_IMPACT_LEVEL_NORMAL = "normal"
ADMIN_WASTE_IMPACT_LEVEL_HIGH = "high"

AUDIT_ACTION_ADMIN_WASTE_CONFIRMED = "admin.waste.confirmed"
AUDIT_ACTION_ADMIN_WASTE_HIGH_IMPACT_NOTIFIED = "admin.waste.high_impact_notified"

VALID_ADMIN_WASTE_IMPACT_LEVELS = {
    ADMIN_WASTE_IMPACT_LEVEL_NORMAL,
    ADMIN_WASTE_IMPACT_LEVEL_HIGH,
}
