CATALOG_CAPTURE_MODE_CLASS_CAPTURE = "CLASS_CAPTURE"
CATALOG_CAPTURE_MODE_PRODUCT_DIRECT = "PRODUCT_DIRECT"

CATALOG_PRODUCT_KIND_FINISHED_GOOD = "FINISHED_GOOD"
CATALOG_PRODUCT_KIND_RAW_MATERIAL = "RAW_MATERIAL"
CATALOG_PRODUCT_KIND_CONSUMABLE = "CONSUMABLE"
CATALOG_PRODUCT_KIND_DISPOSABLE = "DISPOSABLE"

CATALOG_INPUT_PRODUCT_KINDS = (
    CATALOG_PRODUCT_KIND_RAW_MATERIAL,
    CATALOG_PRODUCT_KIND_CONSUMABLE,
    CATALOG_PRODUCT_KIND_DISPOSABLE,
)

CATALOG_USAGE_TYPE_CLEANING_SANITATION = "CLEANING_SANITATION"
CATALOG_USAGE_TYPE_OPERATIONAL_SUPPLY = "OPERATIONAL_SUPPLY"
CATALOG_USAGE_TYPE_OTHER = "OTHER"
CATALOG_USAGE_TYPE_PACKAGING = "PACKAGING"
CATALOG_USAGE_TYPE_PRODUCTION_SUPPLY = "PRODUCTION_SUPPLY"
CATALOG_USAGE_TYPE_RECIPE_INPUT = "RECIPE_INPUT"
