PAYMENT_METHOD_CASH = "CASH"
PAYMENT_METHOD_CARD = "CARD"
PAYMENT_METHOD_MIXED = "MIXED"

DISCOUNT_STATUS_COMMITTED = "COMMITTED"

DISCOUNT_LIST_SCOPE_CURRENT_SHIFT = "CURRENT_SHIFT"
DISCOUNT_LIST_SCOPE_TODAY = "TODAY"
DISCOUNT_LIST_SCOPE_RECENT = "RECENT"

DISCOUNT_CATEGORY_EMPLOYEE_INSURANCE = "EMPLOYEE_INSURANCE"
DISCOUNT_CATEGORY_EMPLOYEE_LOAN = "EMPLOYEE_LOAN"
DISCOUNT_CATEGORY_INTERNAL_CHARGE = "INTERNAL_CHARGE"
DISCOUNT_CATEGORY_PAYROLL_ADVANCE_ADJUSTMENT = "PAYROLL_ADVANCE_ADJUSTMENT"
DISCOUNT_CATEGORY_OTHER = "OTHER"

SUPPORTED_OPERATIONAL_DISCOUNT_METHOD_CODES = {
    PAYMENT_METHOD_CASH,
    PAYMENT_METHOD_CARD,
}
VALID_OPERATIONAL_DISCOUNT_METHOD_CODES = {
    PAYMENT_METHOD_CASH,
    PAYMENT_METHOD_CARD,
    PAYMENT_METHOD_MIXED,
}
VALID_OPERATIONAL_DISCOUNT_STATUS_CODES = {
    DISCOUNT_STATUS_COMMITTED,
}
VALID_OPERATIONAL_DISCOUNT_LIST_SCOPES = {
    DISCOUNT_LIST_SCOPE_CURRENT_SHIFT,
    DISCOUNT_LIST_SCOPE_TODAY,
    DISCOUNT_LIST_SCOPE_RECENT,
}
VALID_OPERATIONAL_DISCOUNT_CATEGORY_CODES = {
    DISCOUNT_CATEGORY_EMPLOYEE_INSURANCE,
    DISCOUNT_CATEGORY_EMPLOYEE_LOAN,
    DISCOUNT_CATEGORY_INTERNAL_CHARGE,
    DISCOUNT_CATEGORY_PAYROLL_ADVANCE_ADJUSTMENT,
    DISCOUNT_CATEGORY_OTHER,
}

AUDIT_ACTION_OPERATIONAL_DISCOUNT_COMMITTED = "operational_discount.committed"
AUDIT_ACTION_OPERATIONAL_DISCOUNT_HIGH_VALUE_ALERT_REQUESTED = (
    "operational_discount.high_value_alert_requested"
)
OPERATIONAL_DISCOUNT_RESOURCE_TYPE = "operational_discount"
OUTBOX_EVENT_OPERATIONAL_DISCOUNT_COMMITTED_V1 = "operational_discount.committed.v1"
OUTBOX_EVENT_OPERATIONAL_DISCOUNT_HIGH_VALUE_ALERT_V1 = (
    "operational_discount.high_value_alert.v1"
)
