PAYMENT_METHOD_CASH = "CASH"
PAYMENT_METHOD_CARD = "CARD"
PAYMENT_METHOD_MIXED = "MIXED"

DISCOUNT_STATUS_COMMITTED = "COMMITTED"

DISCOUNT_LIST_SCOPE_CURRENT_SHIFT = "CURRENT_SHIFT"
DISCOUNT_LIST_SCOPE_TODAY = "TODAY"
DISCOUNT_LIST_SCOPE_RECENT = "RECENT"

DISCOUNT_CATEGORY_EMPLOYEE_INSURANCE = "EMPLOYEE_INSURANCE"
DISCOUNT_CATEGORY_EMPLOYEE_LOAN = "EMPLOYEE_LOAN"
DISCOUNT_CATEGORY_INTERNAL_CHARGE = "INTERNAL_CHARGE"
DISCOUNT_CATEGORY_PAYROLL_ADVANCE_ADJUSTMENT = "PAYROLL_ADVANCE_ADJUSTMENT"
DISCOUNT_CATEGORY_OTHER = "OTHER"

SUPPORTED_OPERATIONAL_DISCOUNT_METHOD_CODES = {
    PAYMENT_METHOD_CASH,
    PAYMENT_METHOD_CARD,
}
VALID_OPERATIONAL_DISCOUNT_METHOD_CODES = {
    PAYMENT_METHOD_CASH,
    PAYMENT_METHOD_CARD,
    PAYMENT_METHOD_MIXED,
}
VALID_OPERATIONAL_DISCOUNT_STATUS_CODES = {
    DISCOUNT_STATUS_COMMITTED,
}
VALID_OPERATIONAL_DISCOUNT_LIST_SCOPES = {
    DISCOUNT_LIST_SCOPE_CURRENT_SHIFT,
    DISCOUNT_LIST_SCOPE_TODAY,
    DISCOUNT_LIST_SCOPE_RECENT,
}
VALID_OPERATIONAL_DISCOUNT_CATEGORY_CODES = {
    DISCOUNT_CATEGORY_EMPLOYEE_INSURANCE,
    DISCOUNT_CATEGORY_EMPLOYEE_LOAN,
    DISCOUNT_CATEGORY_INTERNAL_CHARGE,
    DISCOUNT_CATEGORY_PAYROLL_ADVANCE_ADJUSTMENT,
    DISCOUNT_CATEGORY_OTHER,
}

AUDIT_ACTION_OPERATIONAL_DISCOUNT_COMMITTED = "operational_discount.committed"
AUDIT_ACTION_OPERATIONAL_DISCOUNT_HIGH_VALUE_ALERT_REQUESTED = (
    "operational_discount.high_value_alert_requested"
)
OPERATIONAL_DISCOUNT_RESOURCE_TYPE = "operational_discount"
OUTBOX_EVENT_OPERATIONAL_DISCOUNT_COMMITTED_V1 = "operational_discount.committed.v1"
OUTBOX_EVENT_OPERATIONAL_DISCOUNT_HIGH_VALUE_ALERT_V1 = (
    "operational_discount.high_value_alert.v1"
)

COMMERCIAL_DISCOUNT_TYPE_PERCENTAGE = "PERCENTAGE"
COMMERCIAL_DISCOUNT_TYPE_FIXED_AMOUNT = "FIXED_AMOUNT"

COMMERCIAL_DISCOUNT_SCOPE_GLOBAL = "GLOBAL"
COMMERCIAL_DISCOUNT_SCOPE_PRODUCT = "PRODUCT"
COMMERCIAL_DISCOUNT_SCOPE_CLASS = "CLASS"

COMMERCIAL_DISCOUNT_STATUS_ACTIVE = "ACTIVE"
COMMERCIAL_DISCOUNT_STATUS_INACTIVE = "INACTIVE"
COMMERCIAL_DISCOUNT_STATUS_ARCHIVED = "ARCHIVED"

VALID_COMMERCIAL_DISCOUNT_TYPES = {
    COMMERCIAL_DISCOUNT_TYPE_PERCENTAGE,
    COMMERCIAL_DISCOUNT_TYPE_FIXED_AMOUNT,
}
VALID_COMMERCIAL_DISCOUNT_SCOPES = {
    COMMERCIAL_DISCOUNT_SCOPE_GLOBAL,
    COMMERCIAL_DISCOUNT_SCOPE_PRODUCT,
    COMMERCIAL_DISCOUNT_SCOPE_CLASS,
}
VALID_COMMERCIAL_DISCOUNT_STATUSES = {
    COMMERCIAL_DISCOUNT_STATUS_ACTIVE,
    COMMERCIAL_DISCOUNT_STATUS_INACTIVE,
    COMMERCIAL_DISCOUNT_STATUS_ARCHIVED,
}

COMMERCIAL_DISCOUNT_RESOURCE_TYPE = "commercial_discount"
AUDIT_ACTION_COMMERCIAL_DISCOUNT_CREATED = "admin.commercial_discount.created"
AUDIT_ACTION_COMMERCIAL_DISCOUNT_UPDATED = "admin.commercial_discount.updated"
OUTBOX_EVENT_COMMERCIAL_DISCOUNT_CREATED_V1 = "admin.commercial_discount.created.v1"
OUTBOX_EVENT_COMMERCIAL_DISCOUNT_UPDATED_V1 = "admin.commercial_discount.updated.v1"
