from __future__ import annotations

RETURN_STATUS_COMMITTED = "COMMITTED"

RETURN_REFUND_METHOD_CASH = "CASH"
RETURN_REFUND_METHOD_CARD = "CARD"
RETURN_REFUND_METHOD_MIXED = "MIXED"

RETURN_REASON_CUSTOMER_REGRET = "CUSTOMER_REGRET"
RETURN_REASON_WRONG_ITEM = "WRONG_ITEM"
RETURN_REASON_QUALITY_ISSUE = "QUALITY_ISSUE"
RETURN_REASON_DAMAGED_ON_DELIVERY = "DAMAGED_ON_DELIVERY"
RETURN_REASON_OTHER = "OTHER"

RETURN_SCOPE_CURRENT_SHIFT = "CURRENT_SHIFT"
RETURN_SCOPE_TODAY = "TODAY"
RETURN_SCOPE_RECENT = "RECENT"

RETURN_DISPOSITION_RESTOCK_COUNTER = "RESTOCK_COUNTER"
RETURN_DISPOSITION_RESTOCK_BACKROOM = "RESTOCK_BACKROOM"
RETURN_DISPOSITION_SEND_TO_WASTE = "SEND_TO_WASTE"

VALID_RETURN_SCOPES = {
    RETURN_SCOPE_CURRENT_SHIFT,
    RETURN_SCOPE_TODAY,
    RETURN_SCOPE_RECENT,
}

VALID_RETURN_REFUND_METHOD_CODES = {
    RETURN_REFUND_METHOD_CASH,
}

VISIBLE_RETURN_REFUND_METHOD_CODES = (
    RETURN_REFUND_METHOD_CASH,
    RETURN_REFUND_METHOD_CARD,
    RETURN_REFUND_METHOD_MIXED,
)

RETURN_REASON_DEFINITIONS = (
    (RETURN_REASON_CUSTOMER_REGRET, "Cliente cambio de opinion", 10),
    (RETURN_REASON_WRONG_ITEM, "Producto incorrecto", 20),
    (RETURN_REASON_QUALITY_ISSUE, "Problema de calidad", 30),
    (RETURN_REASON_DAMAGED_ON_DELIVERY, "Danado al entregar", 40),
    (RETURN_REASON_OTHER, "Otro", 50),
)

VALID_RETURN_REASON_CODES = frozenset(
    reason_code for reason_code, _, _ in RETURN_REASON_DEFINITIONS
)

VALID_RETURN_DISPOSITION_CODES = {
    RETURN_DISPOSITION_RESTOCK_COUNTER,
    RETURN_DISPOSITION_RESTOCK_BACKROOM,
    RETURN_DISPOSITION_SEND_TO_WASTE,
}

OUTBOX_EVENT_SALE_RETURN_COMMITTED_V1 = "sale_return.committed.v1"
OUTBOX_EVENT_SALE_RETURN_BACKOFFICE_REVIEW_REQUESTED_V1 = (
    "sale_return.backoffice_review_requested.v1"
)
