from __future__ import annotations

CLEANING_LOG_STATUS_SCHEDULED = "SCHEDULED"
CLEANING_LOG_STATUS_PENDING = "PENDING"
CLEANING_LOG_STATUS_IN_PROGRESS = "IN_PROGRESS"
CLEANING_LOG_STATUS_COMPLETED = "COMPLETED"
CLEANING_LOG_STATUS_MISSED = "MISSED"
CLEANING_LOG_STATUS_CANCELLED = "CANCELLED"
CLEANING_LOG_STATUS_REQUIRES_REVIEW = "REQUIRES_REVIEW"

VALID_CLEANING_LOG_STATUSES = {
    CLEANING_LOG_STATUS_SCHEDULED,
    CLEANING_LOG_STATUS_PENDING,
    CLEANING_LOG_STATUS_IN_PROGRESS,
    CLEANING_LOG_STATUS_COMPLETED,
    CLEANING_LOG_STATUS_MISSED,
    CLEANING_LOG_STATUS_CANCELLED,
    CLEANING_LOG_STATUS_REQUIRES_REVIEW,
}

CLEANING_AREA_TYPE_PRODUCTION = "PRODUCTION_AREA"
CLEANING_AREA_TYPE_COUNTER = "COUNTER_DISPLAY"
CLEANING_AREA_TYPE_STORAGE = "STORAGE"
CLEANING_AREA_TYPE_RESTROOM = "RESTROOM"
CLEANING_AREA_TYPE_CUSTOMER = "CUSTOMER_AREA"
CLEANING_AREA_TYPE_EQUIPMENT = "EQUIPMENT"
CLEANING_AREA_TYPE_EXTERIOR = "EXTERIOR"
CLEANING_AREA_TYPE_OTHER = "OTHER"

VALID_CLEANING_AREA_TYPES = {
    CLEANING_AREA_TYPE_PRODUCTION,
    CLEANING_AREA_TYPE_COUNTER,
    CLEANING_AREA_TYPE_STORAGE,
    CLEANING_AREA_TYPE_RESTROOM,
    CLEANING_AREA_TYPE_CUSTOMER,
    CLEANING_AREA_TYPE_EQUIPMENT,
    CLEANING_AREA_TYPE_EXTERIOR,
    CLEANING_AREA_TYPE_OTHER,
}

CLEANING_FREQUENCY_PER_SHIFT = "PER_SHIFT"
CLEANING_FREQUENCY_DAILY = "DAILY"
CLEANING_FREQUENCY_WEEKLY = "WEEKLY"
CLEANING_FREQUENCY_MONTHLY = "MONTHLY"
CLEANING_FREQUENCY_AS_NEEDED = "AS_NEEDED"

VALID_CLEANING_FREQUENCIES = {
    CLEANING_FREQUENCY_PER_SHIFT,
    CLEANING_FREQUENCY_DAILY,
    CLEANING_FREQUENCY_WEEKLY,
    CLEANING_FREQUENCY_MONTHLY,
    CLEANING_FREQUENCY_AS_NEEDED,
}

CLEANING_TYPE_ROUTINE = "ROUTINE"
CLEANING_TYPE_DEEP = "DEEP_CLEANING"
CLEANING_TYPE_EQUIPMENT = "EQUIPMENT"
CLEANING_TYPE_SANITATION = "SANITATION"
CLEANING_TYPE_SPILL_RESPONSE = "SPILL_RESPONSE"
CLEANING_TYPE_OTHER = "OTHER"

VALID_CLEANING_TYPES = {
    CLEANING_TYPE_ROUTINE,
    CLEANING_TYPE_DEEP,
    CLEANING_TYPE_EQUIPMENT,
    CLEANING_TYPE_SANITATION,
    CLEANING_TYPE_SPILL_RESPONSE,
    CLEANING_TYPE_OTHER,
}

CLEANING_RISK_LOW = "LOW"
CLEANING_RISK_MEDIUM = "MEDIUM"
CLEANING_RISK_HIGH = "HIGH"
CLEANING_RISK_CRITICAL = "CRITICAL"

VALID_CLEANING_RISK_LEVELS = {
    CLEANING_RISK_LOW,
    CLEANING_RISK_MEDIUM,
    CLEANING_RISK_HIGH,
    CLEANING_RISK_CRITICAL,
}

CLEANING_SHIFT_MORNING = "MORNING"
CLEANING_SHIFT_AFTERNOON = "AFTERNOON"
CLEANING_SHIFT_NIGHT = "NIGHT"
CLEANING_SHIFT_MIXED = "MIXED"

VALID_CLEANING_SHIFTS = {
    CLEANING_SHIFT_MORNING,
    CLEANING_SHIFT_AFTERNOON,
    CLEANING_SHIFT_NIGHT,
    CLEANING_SHIFT_MIXED,
}

CLEANING_WARNING_OK = "ok"
CLEANING_WARNING_OVERDUE = "overdue"
CLEANING_WARNING_INCOMPLETE = "incomplete"
CLEANING_WARNING_HIGH_RISK = "high_risk"
CLEANING_WARNING_REVIEW = "review"

CLEANING_RESOURCE_TYPE = "cleaning_log"
AUDIT_ACTION_CLEANING_LOG_CREATED = "admin.cleaning_log.created"
AUDIT_ACTION_CLEANING_LOG_COMPLETED = "admin.cleaning_log.completed"
AUDIT_ACTION_CLEANING_LOG_CANCELLED = "admin.cleaning_log.cancelled"
AUDIT_ACTION_CLEANING_LOG_HIGH_RISK_NOTIFIED = "admin.cleaning_log.high_risk.notified"

OUTBOX_EVENT_CLEANING_LOG_CREATED_V1 = "cleaning_log.created.v1"
OUTBOX_EVENT_CLEANING_LOG_COMPLETED_V1 = "cleaning_log.completed.v1"
OUTBOX_EVENT_CLEANING_LOG_CANCELLED_V1 = "cleaning_log.cancelled.v1"
OUTBOX_EVENT_CLEANING_LOG_HIGH_RISK_ALERT_V1 = "cleaning_log.high_risk_alert.v1"

SANITARY_STATUS_SCHEDULED = "SCHEDULED"
SANITARY_STATUS_PENDING = "PENDING"
SANITARY_STATUS_IN_PROGRESS = "IN_PROGRESS"
SANITARY_STATUS_COMPLETED = "COMPLETED"
SANITARY_STATUS_CANCELLED = "CANCELLED"
SANITARY_STATUS_REQUIRES_FOLLOW_UP = "REQUIRES_FOLLOW_UP"

VALID_SANITARY_STATUSES = {
    SANITARY_STATUS_SCHEDULED,
    SANITARY_STATUS_PENDING,
    SANITARY_STATUS_IN_PROGRESS,
    SANITARY_STATUS_COMPLETED,
    SANITARY_STATUS_CANCELLED,
    SANITARY_STATUS_REQUIRES_FOLLOW_UP,
}

SANITARY_RESULT_NOT_EVALUATED = "NOT_EVALUATED"
SANITARY_RESULT_PASSED = "PASSED"
SANITARY_RESULT_FAILED = "FAILED"
SANITARY_RESULT_PARTIAL = "PARTIAL"

VALID_SANITARY_RESULTS = {
    SANITARY_RESULT_NOT_EVALUATED,
    SANITARY_RESULT_PASSED,
    SANITARY_RESULT_FAILED,
    SANITARY_RESULT_PARTIAL,
}

SANITARY_ITEM_RESULT_PENDING = "PENDING"
SANITARY_ITEM_RESULT_PASSED = "PASSED"
SANITARY_ITEM_RESULT_FAILED = "FAILED"
SANITARY_ITEM_RESULT_NOT_APPLICABLE = "NOT_APPLICABLE"

VALID_SANITARY_ITEM_RESULTS = {
    SANITARY_ITEM_RESULT_PENDING,
    SANITARY_ITEM_RESULT_PASSED,
    SANITARY_ITEM_RESULT_FAILED,
    SANITARY_ITEM_RESULT_NOT_APPLICABLE,
}

SANITARY_PROCESS_STORAGE = "STORAGE"
SANITARY_PROCESS_PRODUCTION = "PRODUCTION"
SANITARY_PROCESS_DISPLAY = "DISPLAY"
SANITARY_PROCESS_EQUIPMENT = "EQUIPMENT"
SANITARY_PROCESS_SANITATION = "SANITATION"
SANITARY_PROCESS_OTHER = "OTHER"

VALID_SANITARY_PROCESS_TYPES = {
    SANITARY_PROCESS_STORAGE,
    SANITARY_PROCESS_PRODUCTION,
    SANITARY_PROCESS_DISPLAY,
    SANITARY_PROCESS_EQUIPMENT,
    SANITARY_PROCESS_SANITATION,
    SANITARY_PROCESS_OTHER,
}

SANITARY_WARNING_OK = "ok"
SANITARY_WARNING_OVERDUE = "overdue"
SANITARY_WARNING_FAILED = "failed"
SANITARY_WARNING_HIGH_RISK = "high_risk"
SANITARY_WARNING_FOLLOW_UP = "follow_up"

SANITARY_RESOURCE_TYPE = "sanitary_verification"
AUDIT_ACTION_SANITARY_VERIFICATION_CREATED = "admin.sanitary_verification.created"
AUDIT_ACTION_SANITARY_VERIFICATION_STARTED = "admin.sanitary_verification.started"
AUDIT_ACTION_SANITARY_VERIFICATION_COMPLETED = "admin.sanitary_verification.completed"
AUDIT_ACTION_SANITARY_VERIFICATION_CANCELLED = "admin.sanitary_verification.cancelled"
AUDIT_ACTION_SANITARY_VERIFICATION_HIGH_RISK_NOTIFIED = (
    "admin.sanitary_verification.high_risk.notified"
)

OUTBOX_EVENT_SANITARY_VERIFICATION_CREATED_V1 = "sanitary_verification.created.v1"
OUTBOX_EVENT_SANITARY_VERIFICATION_STARTED_V1 = "sanitary_verification.started.v1"
OUTBOX_EVENT_SANITARY_VERIFICATION_COMPLETED_V1 = "sanitary_verification.completed.v1"
OUTBOX_EVENT_SANITARY_VERIFICATION_CANCELLED_V1 = "sanitary_verification.cancelled.v1"
OUTBOX_EVENT_SANITARY_VERIFICATION_HIGH_RISK_ALERT_V1 = (
    "sanitary_verification.high_risk_alert.v1"
)

EQUIPMENT_STATUS_OPERATIONAL = "OPERATIONAL"
EQUIPMENT_STATUS_OUT_OF_SERVICE = "OUT_OF_SERVICE"
EQUIPMENT_STATUS_UNDER_MAINTENANCE = "UNDER_MAINTENANCE"
EQUIPMENT_STATUS_RETIRED = "RETIRED"
EQUIPMENT_STATUS_INACTIVE = "INACTIVE"

VALID_EQUIPMENT_OPERATIONAL_STATUSES = {
    EQUIPMENT_STATUS_OPERATIONAL,
    EQUIPMENT_STATUS_OUT_OF_SERVICE,
    EQUIPMENT_STATUS_UNDER_MAINTENANCE,
    EQUIPMENT_STATUS_RETIRED,
    EQUIPMENT_STATUS_INACTIVE,
}

EQUIPMENT_TYPE_OVEN = "OVEN"
EQUIPMENT_TYPE_MIXER = "MIXER"
EQUIPMENT_TYPE_REFRIGERATION = "REFRIGERATION"
EQUIPMENT_TYPE_DISPLAY_CASE = "DISPLAY_CASE"
EQUIPMENT_TYPE_SCALE = "SCALE"
EQUIPMENT_TYPE_PACKAGING = "PACKAGING"
EQUIPMENT_TYPE_SANITATION = "SANITATION"
EQUIPMENT_TYPE_OTHER = "OTHER"

VALID_EQUIPMENT_TYPES = {
    EQUIPMENT_TYPE_OVEN,
    EQUIPMENT_TYPE_MIXER,
    EQUIPMENT_TYPE_REFRIGERATION,
    EQUIPMENT_TYPE_DISPLAY_CASE,
    EQUIPMENT_TYPE_SCALE,
    EQUIPMENT_TYPE_PACKAGING,
    EQUIPMENT_TYPE_SANITATION,
    EQUIPMENT_TYPE_OTHER,
}

EQUIPMENT_AREA_TYPE_PRODUCTION = "PRODUCTION"
EQUIPMENT_AREA_TYPE_REFRIGERATION = "REFRIGERATION"
EQUIPMENT_AREA_TYPE_DISPLAY_COUNTER = "DISPLAY_COUNTER"
EQUIPMENT_AREA_TYPE_STORAGE = "STORAGE"
EQUIPMENT_AREA_TYPE_CLEANING_SANITATION = "CLEANING_SANITATION"
EQUIPMENT_AREA_TYPE_OTHER = "OTHER"

VALID_EQUIPMENT_AREA_TYPES = {
    EQUIPMENT_AREA_TYPE_PRODUCTION,
    EQUIPMENT_AREA_TYPE_REFRIGERATION,
    EQUIPMENT_AREA_TYPE_DISPLAY_COUNTER,
    EQUIPMENT_AREA_TYPE_STORAGE,
    EQUIPMENT_AREA_TYPE_CLEANING_SANITATION,
    EQUIPMENT_AREA_TYPE_OTHER,
}

MAINTENANCE_TYPE_PREVENTIVE = "PREVENTIVE"
MAINTENANCE_TYPE_CORRECTIVE = "CORRECTIVE"
MAINTENANCE_TYPE_INSPECTION = "INSPECTION"
MAINTENANCE_TYPE_CALIBRATION = "CALIBRATION"
MAINTENANCE_TYPE_CLEANING_TECHNICAL = "CLEANING_TECHNICAL"

VALID_MAINTENANCE_TYPES = {
    MAINTENANCE_TYPE_PREVENTIVE,
    MAINTENANCE_TYPE_CORRECTIVE,
    MAINTENANCE_TYPE_INSPECTION,
    MAINTENANCE_TYPE_CALIBRATION,
    MAINTENANCE_TYPE_CLEANING_TECHNICAL,
}

MAINTENANCE_STATUS_SCHEDULED = "SCHEDULED"
MAINTENANCE_STATUS_PENDING = "PENDING"
MAINTENANCE_STATUS_IN_PROGRESS = "IN_PROGRESS"
MAINTENANCE_STATUS_COMPLETED = "COMPLETED"
MAINTENANCE_STATUS_OVERDUE = "OVERDUE"
MAINTENANCE_STATUS_CANCELLED = "CANCELLED"

VALID_MAINTENANCE_STATUSES = {
    MAINTENANCE_STATUS_SCHEDULED,
    MAINTENANCE_STATUS_PENDING,
    MAINTENANCE_STATUS_IN_PROGRESS,
    MAINTENANCE_STATUS_COMPLETED,
    MAINTENANCE_STATUS_OVERDUE,
    MAINTENANCE_STATUS_CANCELLED,
}

MAINTENANCE_RESULT_NOT_COMPLETED = "NOT_COMPLETED"
MAINTENANCE_RESULT_COMPLETED_SUCCESSFULLY = "COMPLETED_SUCCESSFULLY"
MAINTENANCE_RESULT_COMPLETED_WITH_OBSERVATIONS = "COMPLETED_WITH_OBSERVATIONS"
MAINTENANCE_RESULT_FAILED = "FAILED"
MAINTENANCE_RESULT_REQUIRES_FOLLOW_UP = "REQUIRES_FOLLOW_UP"
MAINTENANCE_RESULT_CANCELLED = "CANCELLED"

VALID_MAINTENANCE_RESULTS = {
    MAINTENANCE_RESULT_NOT_COMPLETED,
    MAINTENANCE_RESULT_COMPLETED_SUCCESSFULLY,
    MAINTENANCE_RESULT_COMPLETED_WITH_OBSERVATIONS,
    MAINTENANCE_RESULT_FAILED,
    MAINTENANCE_RESULT_REQUIRES_FOLLOW_UP,
    MAINTENANCE_RESULT_CANCELLED,
}

EQUIPMENT_WARNING_OK = "ok"
EQUIPMENT_WARNING_OVERDUE = "overdue"
EQUIPMENT_WARNING_OUT_OF_SERVICE = "out_of_service"
EQUIPMENT_WARNING_UNDER_MAINTENANCE = "under_maintenance"
EQUIPMENT_WARNING_HIGH_RISK = "high_risk"
EQUIPMENT_WARNING_FOLLOW_UP = "follow_up"

EQUIPMENT_RESOURCE_TYPE = "equipment_asset"
MAINTENANCE_RESOURCE_TYPE = "equipment_maintenance_record"

AUDIT_ACTION_EQUIPMENT_CREATED = "admin.equipment.created"
AUDIT_ACTION_EQUIPMENT_UPDATED = "admin.equipment.updated"
AUDIT_ACTION_EQUIPMENT_STATUS_CHANGED = "admin.equipment.status_changed"
AUDIT_ACTION_EQUIPMENT_HIGH_RISK_NOTIFIED = "admin.equipment.high_risk.notified"
AUDIT_ACTION_MAINTENANCE_CREATED = "admin.equipment_maintenance.created"
AUDIT_ACTION_MAINTENANCE_STARTED = "admin.equipment_maintenance.started"
AUDIT_ACTION_MAINTENANCE_COMPLETED = "admin.equipment_maintenance.completed"
AUDIT_ACTION_MAINTENANCE_CANCELLED = "admin.equipment_maintenance.cancelled"

OUTBOX_EVENT_EQUIPMENT_CREATED_V1 = "equipment.created.v1"
OUTBOX_EVENT_EQUIPMENT_UPDATED_V1 = "equipment.updated.v1"
OUTBOX_EVENT_EQUIPMENT_STATUS_CHANGED_V1 = "equipment.status_changed.v1"
OUTBOX_EVENT_EQUIPMENT_HIGH_RISK_ALERT_V1 = "equipment.high_risk_alert.v1"
OUTBOX_EVENT_MAINTENANCE_CREATED_V1 = "equipment_maintenance.created.v1"
OUTBOX_EVENT_MAINTENANCE_STARTED_V1 = "equipment_maintenance.started.v1"
OUTBOX_EVENT_MAINTENANCE_COMPLETED_V1 = "equipment_maintenance.completed.v1"
OUTBOX_EVENT_MAINTENANCE_CANCELLED_V1 = "equipment_maintenance.cancelled.v1"

INCIDENT_STATUS_OPEN = "OPEN"
INCIDENT_STATUS_IN_REVIEW = "IN_REVIEW"
INCIDENT_STATUS_IN_PROGRESS = "IN_PROGRESS"
INCIDENT_STATUS_WAITING_ACTION = "WAITING_ACTION"
INCIDENT_STATUS_RESOLVED = "RESOLVED"
INCIDENT_STATUS_CLOSED = "CLOSED"
INCIDENT_STATUS_CANCELLED = "CANCELLED"

VALID_INCIDENT_STATUSES = {
    INCIDENT_STATUS_OPEN,
    INCIDENT_STATUS_IN_REVIEW,
    INCIDENT_STATUS_IN_PROGRESS,
    INCIDENT_STATUS_WAITING_ACTION,
    INCIDENT_STATUS_RESOLVED,
    INCIDENT_STATUS_CLOSED,
    INCIDENT_STATUS_CANCELLED,
}

INCIDENT_SEVERITY_LOW = "LOW"
INCIDENT_SEVERITY_MEDIUM = "MEDIUM"
INCIDENT_SEVERITY_HIGH = "HIGH"
INCIDENT_SEVERITY_CRITICAL = "CRITICAL"

VALID_INCIDENT_SEVERITIES = {
    INCIDENT_SEVERITY_LOW,
    INCIDENT_SEVERITY_MEDIUM,
    INCIDENT_SEVERITY_HIGH,
    INCIDENT_SEVERITY_CRITICAL,
}

INCIDENT_TYPE_SANITATION_ISSUE = "SANITATION_ISSUE"
INCIDENT_TYPE_CLEANING_NON_COMPLIANCE = "CLEANING_NON_COMPLIANCE"
INCIDENT_TYPE_EQUIPMENT_FAILURE = "EQUIPMENT_FAILURE"
INCIDENT_TYPE_PRODUCTION_ISSUE = "PRODUCTION_ISSUE"
INCIDENT_TYPE_INVENTORY_ISSUE = "INVENTORY_ISSUE"
INCIDENT_TYPE_TRANSFER_ISSUE = "TRANSFER_ISSUE"
INCIDENT_TYPE_WASTE_ISSUE = "WASTE_ISSUE"
INCIDENT_TYPE_SAFETY_ISSUE = "SAFETY_ISSUE"
INCIDENT_TYPE_CUSTOMER_COMPLAINT = "CUSTOMER_COMPLAINT"
INCIDENT_TYPE_PROCESS_DEVIATION = "PROCESS_DEVIATION"
INCIDENT_TYPE_OTHER = "OTHER"

VALID_INCIDENT_TYPES = {
    INCIDENT_TYPE_SANITATION_ISSUE,
    INCIDENT_TYPE_CLEANING_NON_COMPLIANCE,
    INCIDENT_TYPE_EQUIPMENT_FAILURE,
    INCIDENT_TYPE_PRODUCTION_ISSUE,
    INCIDENT_TYPE_INVENTORY_ISSUE,
    INCIDENT_TYPE_TRANSFER_ISSUE,
    INCIDENT_TYPE_WASTE_ISSUE,
    INCIDENT_TYPE_SAFETY_ISSUE,
    INCIDENT_TYPE_CUSTOMER_COMPLAINT,
    INCIDENT_TYPE_PROCESS_DEVIATION,
    INCIDENT_TYPE_OTHER,
}

INCIDENT_SOURCE_MANUAL = "MANUAL"
INCIDENT_SOURCE_CLEANING_LOG = "CLEANING_LOG"
INCIDENT_SOURCE_SANITARY_VERIFICATION = "SANITARY_VERIFICATION"
INCIDENT_SOURCE_EQUIPMENT = "EQUIPMENT"
INCIDENT_SOURCE_PRODUCTION = "PRODUCTION"
INCIDENT_SOURCE_INVENTORY = "INVENTORY"
INCIDENT_SOURCE_TRANSFER = "TRANSFER"
INCIDENT_SOURCE_WASTE_MERMA = "WASTE_MERMA"
INCIDENT_SOURCE_CUSTOMER_REPORT = "CUSTOMER_REPORT"
INCIDENT_SOURCE_CORRECTION = "CORRECTION"

VALID_INCIDENT_SOURCE_TYPES = {
    INCIDENT_SOURCE_MANUAL,
    INCIDENT_SOURCE_CLEANING_LOG,
    INCIDENT_SOURCE_SANITARY_VERIFICATION,
    INCIDENT_SOURCE_EQUIPMENT,
    INCIDENT_SOURCE_PRODUCTION,
    INCIDENT_SOURCE_INVENTORY,
    INCIDENT_SOURCE_TRANSFER,
    INCIDENT_SOURCE_WASTE_MERMA,
    INCIDENT_SOURCE_CUSTOMER_REPORT,
    INCIDENT_SOURCE_CORRECTION,
}

INCIDENT_WARNING_OK = "ok"
INCIDENT_WARNING_HIGH_RISK = "high_risk"
INCIDENT_WARNING_OVERDUE = "overdue"
INCIDENT_WARNING_UNASSIGNED = "unassigned"
INCIDENT_WARNING_MISSING_EVIDENCE = "missing_evidence"
INCIDENT_WARNING_WAITING_ACTION = "waiting_action"

INCIDENT_RESOURCE_TYPE = "quality_incident"
INCIDENT_FOLLOW_UP_RESOURCE_TYPE = "quality_incident_follow_up"

AUDIT_ACTION_INCIDENT_CREATED = "admin.incident.created"
AUDIT_ACTION_INCIDENT_UPDATED = "admin.incident.updated"
AUDIT_ACTION_INCIDENT_FOLLOW_UP_ADDED = "admin.incident.follow_up_added"
AUDIT_ACTION_INCIDENT_STATUS_CHANGED = "admin.incident.status_changed"
AUDIT_ACTION_INCIDENT_RESOLVED = "admin.incident.resolved"
AUDIT_ACTION_INCIDENT_REOPENED = "admin.incident.reopened"
AUDIT_ACTION_INCIDENT_HIGH_RISK_NOTIFIED = "admin.incident.high_risk.notified"

OUTBOX_EVENT_INCIDENT_CREATED_V1 = "quality_incident.created.v1"
OUTBOX_EVENT_INCIDENT_UPDATED_V1 = "quality_incident.updated.v1"
OUTBOX_EVENT_INCIDENT_FOLLOW_UP_ADDED_V1 = "quality_incident.follow_up_added.v1"
OUTBOX_EVENT_INCIDENT_STATUS_CHANGED_V1 = "quality_incident.status_changed.v1"
OUTBOX_EVENT_INCIDENT_RESOLVED_V1 = "quality_incident.resolved.v1"
OUTBOX_EVENT_INCIDENT_REOPENED_V1 = "quality_incident.reopened.v1"
OUTBOX_EVENT_INCIDENT_HIGH_RISK_ALERT_V1 = "quality_incident.high_risk_alert.v1"
