PURCHASE_DOCUMENT_TYPE_PURCHASE = "PURCHASE"
PURCHASE_DOCUMENT_TYPE_DIRECT_ENTRY = "DIRECT_ENTRY"

PURCHASE_STATUS_DRAFT = "DRAFT"
PURCHASE_STATUS_ORDERED = "ORDERED"
PURCHASE_STATUS_PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
PURCHASE_STATUS_RECEIVED = "RECEIVED"
PURCHASE_STATUS_CANCELLED = "CANCELLED"

PURCHASE_EXTERNAL_DOCUMENT_INVOICE = "INVOICE"
PURCHASE_EXTERNAL_DOCUMENT_REMISSION = "REMISSION"
PURCHASE_EXTERNAL_DOCUMENT_SUPPLIER_NOTE = "SUPPLIER_NOTE"
PURCHASE_EXTERNAL_DOCUMENT_PURCHASE_REFERENCE = "PURCHASE_REFERENCE"
PURCHASE_EXTERNAL_DOCUMENT_OTHER = "OTHER"

PURCHASE_RESOURCE_TYPE = "purchase_document"
PURCHASE_RECEIPT_RESOURCE_TYPE = "purchase_receipt"
PURCHASE_RECEIPT_SOURCE_DOCUMENT_TYPE = "PURCHASE_RECEIPT"

AUDIT_ACTION_ADMIN_PURCHASE_CREATED = "admin.purchase.created"
AUDIT_ACTION_ADMIN_PURCHASE_UPDATED = "admin.purchase.updated"
AUDIT_ACTION_ADMIN_PURCHASE_CONFIRMED = "admin.purchase.confirmed"
AUDIT_ACTION_ADMIN_PURCHASE_RECEIVED = "admin.purchase.received"
AUDIT_ACTION_ADMIN_PURCHASE_CANCELLED = "admin.purchase.cancelled"

OUTBOX_EVENT_ADMIN_PURCHASE_CREATED_V1 = "admin.purchase.created.v1"
OUTBOX_EVENT_ADMIN_PURCHASE_CONFIRMED_V1 = "admin.purchase.confirmed.v1"
OUTBOX_EVENT_ADMIN_PURCHASE_RECEIVED_V1 = "admin.purchase.received.v1"
OUTBOX_EVENT_ADMIN_PURCHASE_CANCELLED_V1 = "admin.purchase.cancelled.v1"

VALID_PURCHASE_DOCUMENT_TYPES = {
    PURCHASE_DOCUMENT_TYPE_PURCHASE,
    PURCHASE_DOCUMENT_TYPE_DIRECT_ENTRY,
}

VALID_PURCHASE_STATUSES = {
    PURCHASE_STATUS_DRAFT,
    PURCHASE_STATUS_ORDERED,
    PURCHASE_STATUS_PARTIALLY_RECEIVED,
    PURCHASE_STATUS_RECEIVED,
    PURCHASE_STATUS_CANCELLED,
}

VALID_PURCHASE_EXTERNAL_DOCUMENT_TYPES = {
    PURCHASE_EXTERNAL_DOCUMENT_INVOICE,
    PURCHASE_EXTERNAL_DOCUMENT_REMISSION,
    PURCHASE_EXTERNAL_DOCUMENT_SUPPLIER_NOTE,
    PURCHASE_EXTERNAL_DOCUMENT_PURCHASE_REFERENCE,
    PURCHASE_EXTERNAL_DOCUMENT_OTHER,
}
