from typing import Final

INVENTORY_LOCATION_BACKROOM = "BACKROOM"
INVENTORY_LOCATION_COUNTER = "COUNTER"
INVENTORY_LOCATION_IN_TRANSIT = "IN_TRANSIT"
INVENTORY_LOCATION_WASTE = "WASTE"

INVENTORY_MOVEMENT_TYPE_MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"
INVENTORY_MOVEMENT_TYPE_STOCK_COUNT_ADJUSTMENT = "STOCK_COUNT_ADJUSTMENT"
INVENTORY_MOVEMENT_TYPE_TRANSFER_DISPATCH = "TRANSFER_DISPATCH"
INVENTORY_MOVEMENT_TYPE_TRANSFER_RECEIPT = "TRANSFER_RECEIPT"
INVENTORY_MOVEMENT_TYPE_PURCHASE_RECEIPT = "PURCHASE_RECEIPT"
INVENTORY_MOVEMENT_TYPE_PRODUCTION_CONSUMPTION = "PRODUCTION_CONSUMPTION"
INVENTORY_MOVEMENT_TYPE_PRODUCTION_OUTPUT = "PRODUCTION_OUTPUT"
INVENTORY_MOVEMENT_TYPE_WASTE_RECORD = "WASTE_RECORD"

INVENTORY_MOVEMENT_DIRECTION_IN = "IN"
INVENTORY_MOVEMENT_DIRECTION_OUT = "OUT"

INVENTORY_ADJUSTMENT_TYPE_INCREASE = "INCREASE"
INVENTORY_ADJUSTMENT_TYPE_DECREASE = "DECREASE"
INVENTORY_ADJUSTMENT_TYPE_SET_COUNTED = "SET_COUNTED"

INVENTORY_STOCK_STATE_IN_STOCK: Final = "in_stock"
INVENTORY_STOCK_STATE_OUT_OF_STOCK: Final = "out_of_stock"
INVENTORY_STOCK_STATE_LOW_STOCK: Final = "low_stock"
INVENTORY_STOCK_STATE_NEGATIVE_STOCK: Final = "negative_stock"

OUTBOX_EVENT_ADMIN_INVENTORY_ADJUSTMENT_CREATED_V1 = "admin.inventory_adjustment.created.v1"

VALID_INVENTORY_LOCATION_CODES = {
    INVENTORY_LOCATION_BACKROOM,
    INVENTORY_LOCATION_COUNTER,
    INVENTORY_LOCATION_IN_TRANSIT,
    INVENTORY_LOCATION_WASTE,
}

VALID_INVENTORY_MOVEMENT_TYPES = {
    INVENTORY_MOVEMENT_TYPE_MANUAL_ADJUSTMENT,
    INVENTORY_MOVEMENT_TYPE_STOCK_COUNT_ADJUSTMENT,
    INVENTORY_MOVEMENT_TYPE_TRANSFER_DISPATCH,
    INVENTORY_MOVEMENT_TYPE_TRANSFER_RECEIPT,
    INVENTORY_MOVEMENT_TYPE_PURCHASE_RECEIPT,
    INVENTORY_MOVEMENT_TYPE_PRODUCTION_CONSUMPTION,
    INVENTORY_MOVEMENT_TYPE_PRODUCTION_OUTPUT,
    INVENTORY_MOVEMENT_TYPE_WASTE_RECORD,
}

VALID_INVENTORY_MOVEMENT_DIRECTIONS = {
    INVENTORY_MOVEMENT_DIRECTION_IN,
    INVENTORY_MOVEMENT_DIRECTION_OUT,
}

VALID_INVENTORY_ADJUSTMENT_TYPES = {
    INVENTORY_ADJUSTMENT_TYPE_INCREASE,
    INVENTORY_ADJUSTMENT_TYPE_DECREASE,
    INVENTORY_ADJUSTMENT_TYPE_SET_COUNTED,
}
