SUPPLIER_STATUS_ACTIVE = "ACTIVE"
SUPPLIER_STATUS_INACTIVE = "INACTIVE"
SUPPLIER_STATUS_BLOCKED = "BLOCKED"

SUPPLIER_CATEGORY_RAW_MATERIALS = "RAW_MATERIALS"
SUPPLIER_CATEGORY_PACKAGING = "PACKAGING"
SUPPLIER_CATEGORY_SERVICES = "SERVICES"
SUPPLIER_CATEGORY_MIXED = "MIXED"
SUPPLIER_CATEGORY_OTHER = "OTHER"

SUPPLIER_PAYMENT_TERMS_CASH = "CASH"
SUPPLIER_PAYMENT_TERMS_CREDIT = "CREDIT"
SUPPLIER_PAYMENT_TERMS_TRANSFER = "TRANSFER"
SUPPLIER_PAYMENT_TERMS_MIXED = "MIXED"

SUPPLIER_WARNING_INFO = "info"
SUPPLIER_WARNING_WARNING = "warning"
SUPPLIER_WARNING_CRITICAL = "critical"

SUPPLIER_RESOURCE_TYPE = "supplier"

AUDIT_ACTION_ADMIN_SUPPLIER_CREATED = "admin.supplier.created"
AUDIT_ACTION_ADMIN_SUPPLIER_UPDATED = "admin.supplier.updated"
AUDIT_ACTION_ADMIN_SUPPLIER_STATUS_CHANGED = "admin.supplier.status_changed"
AUDIT_ACTION_ADMIN_SUPPLIER_CONTACT_CREATED = "admin.supplier.contact.created"
AUDIT_ACTION_ADMIN_SUPPLIER_CONTACT_UPDATED = "admin.supplier.contact.updated"
AUDIT_ACTION_ADMIN_SUPPLIER_PRODUCT_LINKED = "admin.supplier.product.linked"
AUDIT_ACTION_ADMIN_SUPPLIER_PRODUCT_UPDATED = "admin.supplier.product.updated"

OUTBOX_EVENT_ADMIN_SUPPLIER_CREATED_V1 = "admin.supplier.created.v1"
OUTBOX_EVENT_ADMIN_SUPPLIER_UPDATED_V1 = "admin.supplier.updated.v1"
OUTBOX_EVENT_ADMIN_SUPPLIER_STATUS_CHANGED_V1 = "admin.supplier.status_changed.v1"

VALID_SUPPLIER_STATUSES = {
    SUPPLIER_STATUS_ACTIVE,
    SUPPLIER_STATUS_INACTIVE,
    SUPPLIER_STATUS_BLOCKED,
}

VALID_SUPPLIER_CATEGORIES = {
    SUPPLIER_CATEGORY_RAW_MATERIALS,
    SUPPLIER_CATEGORY_PACKAGING,
    SUPPLIER_CATEGORY_SERVICES,
    SUPPLIER_CATEGORY_MIXED,
    SUPPLIER_CATEGORY_OTHER,
}

VALID_SUPPLIER_PAYMENT_TERMS = {
    SUPPLIER_PAYMENT_TERMS_CASH,
    SUPPLIER_PAYMENT_TERMS_CREDIT,
    SUPPLIER_PAYMENT_TERMS_TRANSFER,
    SUPPLIER_PAYMENT_TERMS_MIXED,
}
