"""pos_projection_model_check

Revision ID: 75edb599eaf2
Revises: 865e3ffa51f3
Create Date: 2026-03-22 00:20:20.331519

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "75edb599eaf2"
down_revision: Union[str, Sequence[str], None] = "865e3ffa51f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cash_session",
        "opened_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "cash_session",
        "opening_amount",
        existing_type=sa.NUMERIC(precision=18, scale=2),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "cash_session",
        "status",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.String(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'OPEN'::character varying"),
    )
    op.create_index("ix_cash_session_opened_at", "cash_session", ["opened_at"], unique=False)
    op.create_index("ix_cash_session_status", "cash_session", ["status"], unique=False)
    op.create_index(
        "uq_cash_session_one_open_per_branch",
        "cash_session",
        ["branch_id"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.drop_constraint(
        op.f("fk_cash_session_closed_by_id_user_account"), "cash_session", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_cash_session_closed_by_id_user_account"),
        "cash_session",
        "user_account",
        ["closed_by_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index("ix_payment_created_at", "payment", ["created_at"], unique=False)
    op.create_index("ix_payment_method", "payment", ["method"], unique=False)
    op.alter_column(
        "product",
        "quick_name",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Short label for POS presentation.",
        existing_nullable=True,
    )
    op.alter_column(
        "product",
        "show_in_pos",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Whether this product is visible in POS bootstrap.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "product",
        "is_sellable_in_pos",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Explicit sellability flag for POS presentation.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "product",
        "default_pos_order",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Default backend-provided ordering hint for POS presentation.",
        existing_nullable=False,
        existing_server_default=sa.text("100"),
    )
    op.alter_column(
        "product_category",
        "quick_name",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Short label for POS presentation.",
        existing_nullable=True,
    )
    op.alter_column(
        "product_category",
        "show_in_pos",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Whether this category is visible in POS bootstrap.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "product_category",
        "default_pos_order",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Default backend-provided ordering hint for POS presentation.",
        existing_nullable=False,
        existing_server_default=sa.text("100"),
    )
    op.create_index("ix_production_run_created_at", "production_run", ["created_at"], unique=False)
    op.create_index("ix_sale_created_at", "sale", ["created_at"], unique=False)
    op.create_index("ix_sale_status", "sale", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sale_status", table_name="sale")
    op.drop_index("ix_sale_created_at", table_name="sale")
    op.drop_index("ix_production_run_created_at", table_name="production_run")
    op.alter_column(
        "product_category",
        "default_pos_order",
        existing_type=sa.INTEGER(),
        comment="Default backend-provided ordering hint for POS presentation.",
        existing_nullable=False,
        existing_server_default=sa.text("100"),
    )
    op.alter_column(
        "product_category",
        "show_in_pos",
        existing_type=sa.BOOLEAN(),
        comment="Whether this category is visible in POS bootstrap.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "product_category",
        "quick_name",
        existing_type=sa.TEXT(),
        comment="Short label for POS presentation.",
        existing_nullable=True,
    )
    op.alter_column(
        "product",
        "default_pos_order",
        existing_type=sa.INTEGER(),
        comment="Default backend-provided ordering hint for POS presentation.",
        existing_nullable=False,
        existing_server_default=sa.text("100"),
    )
    op.alter_column(
        "product",
        "is_sellable_in_pos",
        existing_type=sa.BOOLEAN(),
        comment="Explicit sellability flag for POS presentation.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "product",
        "show_in_pos",
        existing_type=sa.BOOLEAN(),
        comment="Whether this product is visible in POS bootstrap.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "product",
        "quick_name",
        existing_type=sa.TEXT(),
        comment="Short label for POS presentation.",
        existing_nullable=True,
    )
    op.drop_index("ix_payment_method", table_name="payment")
    op.drop_index("ix_payment_created_at", table_name="payment")
    op.drop_constraint(
        op.f("fk_cash_session_closed_by_id_user_account"), "cash_session", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_cash_session_closed_by_id_user_account"),
        "cash_session",
        "user_account",
        ["closed_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(
        "uq_cash_session_one_open_per_branch",
        table_name="cash_session",
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.drop_index("ix_cash_session_status", table_name="cash_session")
    op.drop_index("ix_cash_session_opened_at", table_name="cash_session")
    op.alter_column(
        "cash_session",
        "status",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
        existing_server_default=sa.text("'OPEN'::character varying"),
    )
    op.alter_column(
        "cash_session",
        "opening_amount",
        existing_type=sa.NUMERIC(precision=18, scale=2),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "cash_session",
        "opened_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
