"""create product and inventory movement

Revision ID: 8e1d77af65e2
Revises: 4a87fc03a0ce
Create Date: 2026-02-05 20:47:59.936970

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8e1d77af65e2"
down_revision: str | Sequence[str] | None = "4a87fc03a0ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sku", sa.String(length=32), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
    )
    op.create_index(op.f("ix_product_sku"), "product", ["sku"], unique=True)
    op.create_table(
        "inventory_movement",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("branch_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("ref_type", sa.String(length=32), nullable=True),
        sa.Column("ref_id", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
            name=op.f("fk_inventory_movement_branch_id_branch"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user_account.id"],
            name=op.f("fk_inventory_movement_created_by_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_inventory_movement_product_id_product"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movement")),
    )
    op.create_index(
        op.f("ix_inventory_movement_branch_id"),
        "inventory_movement",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movement_created_by_id"),
        "inventory_movement",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movement_product_id"),
        "inventory_movement",
        ["product_id"],
        unique=False,
    )
    op.alter_column(
        "branch",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "branch",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "branch",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_branch_code"), "branch", type_="unique")
    op.create_index(op.f("ix_branch_code"), "branch", ["code"], unique=True)
    op.drop_table_comment(
        "branch", existing_comment="Physical store / location", schema=None
    )
    op.alter_column(
        "role",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "role",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_role_code"), "role", type_="unique")
    op.create_index(op.f("ix_role_code"), "role", ["code"], unique=True)
    op.drop_table_comment(
        "role", existing_comment="Role-based access control entry", schema=None
    )
    op.alter_column(
        "user_account",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user_account",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_account",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_user_account_email"), "user_account", type_="unique")
    op.create_index(
        op.f("ix_user_account_email"), "user_account", ["email"], unique=True
    )
    op.drop_constraint(
        op.f("fk_user_account_branch_id_branch"), "user_account", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_user_account_role_id_role"), "user_account", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_user_account_role_id_role"),
        "user_account",
        "role",
        ["role_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_user_account_branch_id_branch"),
        "user_account",
        "branch",
        ["branch_id"],
        ["id"],
    )
    op.drop_table_comment(
        "user_account", existing_comment="Application user / employee", schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "user_account",
        "Application user / employee",
        existing_comment=None,
        schema=None,
    )
    op.drop_constraint(
        op.f("fk_user_account_branch_id_branch"), "user_account", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_user_account_role_id_role"), "user_account", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_user_account_role_id_role"),
        "user_account",
        "role",
        ["role_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_user_account_branch_id_branch"),
        "user_account",
        "branch",
        ["branch_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_index(op.f("ix_user_account_email"), table_name="user_account")
    op.create_unique_constraint(
        op.f("uq_user_account_email"),
        "user_account",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "user_account",
        "updated_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("now()"),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "user_account",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("now()"),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "user_account",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.create_table_comment(
        "role", "Role-based access control entry", existing_comment=None, schema=None
    )
    op.drop_index(op.f("ix_role_code"), table_name="role")
    op.create_unique_constraint(
        op.f("uq_role_code"), "role", ["code"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "role",
        "updated_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("now()"),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "role",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("now()"),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.create_table_comment(
        "branch", "Physical store / location", existing_comment=None, schema=None
    )
    op.drop_index(op.f("ix_branch_code"), table_name="branch")
    op.create_unique_constraint(
        op.f("uq_branch_code"), "branch", ["code"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "branch",
        "updated_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("now()"),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "branch",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("now()"),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "branch",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_inventory_movement_product_id"), table_name="inventory_movement"
    )
    op.drop_index(
        op.f("ix_inventory_movement_created_by_id"), table_name="inventory_movement"
    )
    op.drop_index(
        op.f("ix_inventory_movement_branch_id"), table_name="inventory_movement"
    )
    op.drop_table("inventory_movement")
    op.drop_index(op.f("ix_product_sku"), table_name="product")
    op.drop_table("product")
    # ### end Alembic commands ###
