PAYMENT_METHOD_CASH = "CASH"
PAYMENT_METHOD_CARD = "CARD"
PAYMENT_METHOD_MIXED = "MIXED"

PAYMENT_STATUS_COMMITTED = "COMMITTED"

PAYMENT_LIST_SCOPE_CURRENT_SHIFT = "CURRENT_SHIFT"
PAYMENT_LIST_SCOPE_TODAY = "TODAY"
PAYMENT_LIST_SCOPE_RECENT = "RECENT"

PAYMENT_CATEGORY_GAS = "GAS"
PAYMENT_CATEGORY_SUPPLIER = "SUPPLIER"
PAYMENT_CATEGORY_SERVICES = "SERVICES"
PAYMENT_CATEGORY_LOGISTICS = "LOGISTICS"
PAYMENT_CATEGORY_PURCHASE = "PURCHASE"
PAYMENT_CATEGORY_OTHER = "OTHER"

SUPPORTED_OPERATIONAL_PAYMENT_METHOD_CODES = {
    PAYMENT_METHOD_CASH,
    PAYMENT_METHOD_CARD,
}
VALID_OPERATIONAL_PAYMENT_METHOD_CODES = {
    PAYMENT_METHOD_CASH,
    PAYMENT_METHOD_CARD,
    PAYMENT_METHOD_MIXED,
}
VALID_OPERATIONAL_PAYMENT_STATUS_CODES = {
    PAYMENT_STATUS_COMMITTED,
}
VALID_OPERATIONAL_PAYMENT_LIST_SCOPES = {
    PAYMENT_LIST_SCOPE_CURRENT_SHIFT,
    PAYMENT_LIST_SCOPE_TODAY,
    PAYMENT_LIST_SCOPE_RECENT,
}
VALID_OPERATIONAL_PAYMENT_CATEGORY_CODES = {
    PAYMENT_CATEGORY_GAS,
    PAYMENT_CATEGORY_SUPPLIER,
    PAYMENT_CATEGORY_SERVICES,
    PAYMENT_CATEGORY_LOGISTICS,
    PAYMENT_CATEGORY_PURCHASE,
    PAYMENT_CATEGORY_OTHER,
}

AUDIT_ACTION_OPERATIONAL_PAYMENT_COMMITTED = "operational_payment.committed"
OPERATIONAL_PAYMENT_RESOURCE_TYPE = "operational_payment"
OUTBOX_EVENT_OPERATIONAL_PAYMENT_COMMITTED_V1 = "operational_payment.committed.v1"
