from zeromerma_api.modules.operations.domain.constants import (
    OPERATION_DOCUMENT_TYPE_BRANCH_TRANSFER_SHIPMENT,
    OPERATION_DOCUMENT_TYPE_COUNTER_TRANSFER,
    OPERATION_DOCUMENT_TYPE_WASTE_RECORD,
)

CORRECTION_TYPE_DELTA_ADJUSTMENT = "DELTA_ADJUSTMENT"
CORRECTION_TYPE_DESTINATION_ADJUSTMENT = "DESTINATION_ADJUSTMENT"
CORRECTION_STATUS_COMMITTED = "COMMITTED"

CORRECTION_REASON_WRONG_QUANTITY = "WRONG_QUANTITY"
CORRECTION_REASON_WRONG_PRODUCT = "WRONG_PRODUCT"
CORRECTION_REASON_DUPLICATE_CAPTURE = "DUPLICATE_CAPTURE"
CORRECTION_REASON_DAMAGED_DURING_HANDLING = "DAMAGED_DURING_HANDLING"
CORRECTION_REASON_COUNT_MISMATCH = "COUNT_MISMATCH"
CORRECTION_REASON_WRONG_DESTINATION = "WRONG_DESTINATION"
CORRECTION_REASON_OTHER = "OTHER"

VALID_CORRECTION_TARGET_DOCUMENT_TYPES = {
    OPERATION_DOCUMENT_TYPE_COUNTER_TRANSFER,
    OPERATION_DOCUMENT_TYPE_WASTE_RECORD,
    OPERATION_DOCUMENT_TYPE_BRANCH_TRANSFER_SHIPMENT,
}

OUTBOX_EVENT_CORRECTION_COMMITTED_V1 = "correction.committed.v1"
OUTBOX_EVENT_CORRECTION_HIGH_IMPACT_ALERT_V1 = "correction.high_impact_alert.v1"
