from __future__ import annotations

TICKET_SCOPE_CURRENT_SHIFT = "CURRENT_SHIFT"
TICKET_SCOPE_TODAY = "TODAY"
TICKET_SCOPE_RECENT = "RECENT"

TICKET_RETURN_STATUS_NOT_RETURNED = "NOT_RETURNED"
TICKET_RETURN_STATUS_PARTIALLY_RETURNED = "PARTIALLY_RETURNED"
TICKET_RETURN_STATUS_FULLY_RETURNED = "FULLY_RETURNED"

VALID_TICKET_SCOPES = {
    TICKET_SCOPE_CURRENT_SHIFT,
    TICKET_SCOPE_TODAY,
    TICKET_SCOPE_RECENT,
}

TICKET_RESOURCE_TYPE = "sale_ticket"
AUDIT_ACTION_TICKET_REPRINTED = "ticket.reprinted"
