SALE_STATUS_CONFIRMED = "CONFIRMED"

SALE_LINE_PHYSICAL_ATTRIBUTION_PENDING_RECONCILIATION = "PENDING_RECONCILIATION"
SALE_LINE_PHYSICAL_ATTRIBUTION_DIRECT_ASSIGNED = "DIRECT_ASSIGNED"
SALE_LINE_PHYSICAL_ATTRIBUTION_RECONCILED = "RECONCILED"

SALE_PAYMENT_METHOD_CASH = "CASH"
SALE_PAYMENT_METHOD_CARD = "CARD"
SALE_PAYMENT_METHOD_MIXED = "MIXED"
VALID_SALE_PAYMENT_METHOD_CODES = frozenset(
    {
        SALE_PAYMENT_METHOD_CASH,
        SALE_PAYMENT_METHOD_CARD,
        SALE_PAYMENT_METHOD_MIXED,
    }
)
NON_CASH_SALE_PAYMENT_METHOD_CODES = frozenset(
    {
        SALE_PAYMENT_METHOD_CARD,
    }
)

CASH_MOVEMENT_DIRECTION_IN = "IN"
CASH_MOVEMENT_DIRECTION_OUT = "OUT"
CASH_MOVEMENT_TYPE_SALE_COLLECTION = "SALE_COLLECTION"
CASH_MOVEMENT_TYPE_OPERATIONAL_PAYMENT = "OPERATIONAL_PAYMENT"
CASH_MOVEMENT_TYPE_OPERATIONAL_DISCOUNT = "OPERATIONAL_DISCOUNT"

OUTBOX_EVENT_SALE_CONFIRMED_V1 = "sale.confirmed.v1"
