# apps/backend/src/zeromerma_api/models/admin.py

from __future__ import (
    annotations,  # 1) delays evaluation of type hints -> avoids circular import issues in 3.11+
)

# 2) Standard library imports (no side effects): typing for lists/optionals, datetime for
#  timestamp types.
from datetime import datetime

# 3) SQLAlchemy ORM primitives for typed mappings in 2.0 style.
from sqlalchemy import BigInteger, Boolean, ForeignKey, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

# 4) Import your shared Declarative Base (one Base across the project keeps metadata coherent
# for Alembic).
from zeromerma_api.models.base import Base


# --------------------------
# Small helper fns for timestamps
# --------------------------
def created_at_col():
    """
    Return a mapped_column configured to let the DATABASE set the value to now()
    on insert time. We use server_default=func.now() so the value is generated by Postgres,
    not by the app clock (more reliable in distributed setups).
    """
    # NOTE: no timezone coercion here; the column type will be TIMESTAMPTZ in migration.
    return mapped_column(default=func.now(), nullable=False)


def updated_at_col():
    """
    Return a mapped_column for 'updated_at' that is initially set to now().
    IMPORTANT: SQLAlchemy won't auto-update this on update; we will update it in code paths that
      modify rows.
    (If you prefer DB triggers later, we can add them—but app-layer updates are enough for MVP.)
    """
    return mapped_column(default=func.now(), nullable=False)


# --------------------------
# Branch model
# --------------------------
class Branch(Base):
    """
    Physical store / location.
    Examples: MAIN, NORTH-01, AIRPORT-KIOSK.

    Data rules:
    - 'code' is a short, UNIQUE, human-readable key you can print on labels and use in configs.
    - 'name' is a free text display name.
    - 'is_active' lets you deactivate a branch without deleting historical records.
    - Timestamps are audit fields; we can add created_by/updated_by later if needed.
    """

    __tablename__ = (
        "branch"  # 5) explicit table name (snake_case) -> stable and predictable in migrations
    )

    # 6) Primary key: BIGINT auto-increment. 'autoincrement=True' on Postgres + BigInteger produces
    #  a bigserial-like sequence.
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)

    # 7) Short stable key. UNIQUE + index=True for fast lookups (e.g., seed/refs). Max length
    #  chosen to fit codes like 'NORTH-01'.
    code: Mapped[str] = mapped_column(String(16), unique=True, index=True)

    # 8) Human-readable label. Text allows long names; if you prefer capped length,
    #  use String(100/150).
    name: Mapped[str] = mapped_column(Text)

    # 9) Operational flag. Default True so new branches are active by default.
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # 10) Audit timestamps. DB default 'now()' assigned via default=func.now() (see helper).
    # Non-nullable for consistent history.
    created_at: Mapped[datetime] = created_at_col()
    updated_at: Mapped[datetime] = updated_at_col()

    # 11) Reverse relationship: a branch has many users. We define this AFTER UserAccount
    #  class exists,
    #     but referencing by string is fine (SQLAlchemy resolves later).
    users: Mapped[list[UserAccount]] = relationship(back_populates="branch")


# --------------------------
# Role model
# --------------------------
class Role(Base):
    """
    Role-based access control primitive.
    Examples (codes): ADMIN, CASHIER, BAKER.

    Data rules:
    - 'code' is UNIQUE and stable; keep it uppercase-with-underscores for clarity.
    - 'name' is a descriptive label for UI (can be localized later).
    - Timestamps for audit.
    """

    __tablename__ = "role"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)

    # UNIQUE + index helps both integrity and performance on lookups like Role(code='ADMIN').
    code: Mapped[str] = mapped_column(String(32), unique=True, index=True)
    name: Mapped[str] = mapped_column(Text)

    created_at: Mapped[datetime] = created_at_col()
    updated_at: Mapped[datetime] = updated_at_col()

    # Reverse relationship: a role has many users.
    users: Mapped[list[UserAccount]] = relationship(back_populates="role")


# --------------------------
# UserAccount model
# --------------------------
class UserAccount(Base):
    """
    Application user / employee (cashier, baker, manager, admin).

    Data rules:
    - Each user belongs to EXACTLY ONE branch (home branch) and ONE role.
      (We can generalize later if needed: multi-branch permissions, many-to-many roles.)
    - 'email' is UNIQUE (login key).
    - 'password_hash' is nullable for system/service users or SSO later (we'll plug auth later).
    - 'is_active' allows soft off-boarding without losing history.
    - Timestamps for audit.
    """

    __tablename__ = "user_account"  # not 'user' to avoid reserved-word collisions across DBs

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)

    # Foreign keys to branch and role. index=True improves join/filter performance.
    # ondelete is enforced at DB level in migration for RESTRICT semantics.
    branch_id: Mapped[int] = mapped_column(ForeignKey("branch.id"), index=True, nullable=False)
    role_id: Mapped[int] = mapped_column(ForeignKey("role.id"), index=True, nullable=False)

    # Unique login identity. Index + unique -> fast/email-based lookups, prevents duplicates.
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True)

    # Display name for UIs and reports. Text gives flexibility (e.g., long names).
    full_name: Mapped[str] = mapped_column(Text)

    # Nullable hash allows creating the user record before setting password
    # (or using external auth later).
    password_hash: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Operational flag. Default True so users start enabled.
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    created_at: Mapped[datetime] = created_at_col()
    updated_at: Mapped[datetime] = updated_at_col()

    # ORM relationships (bidirectional):
    branch: Mapped[Branch] = relationship(back_populates="users")
    role: Mapped[Role] = relationship(back_populates="users")
